applypatch updates to make general

diff --git a/bin/applypatch b/bin/applypatch
--- a/bin/applypatch
+++ b/bin/applypatch
@@ -1,21 +1,43 @@
 #!/bin/sh
 #
 # This tool needs to run 'off Z' (it runs successfully on a Mac)
-# It requires the openssl-1.1.1o tarball to be in the directory
+# It requires the tarball to be in the directory
 # you run this from
 #
 set +x
-rm -rf openssl-1.1.1o
-tar -xvf openssl-1.1.1o.tar.gz
-cd openssl-1.1.1o
-git init 
-git add .
-git commit -m "main"
-git checkout -b openssl
+if [ $# -lt 2 ]; then
+	echo "Syntax: $0 <tarball> <patch dir>" >&2
+	echo "  where <tarball name> is the name of a source tarball" >&2
+	echo "  and <patch dir> is the name of a directory to apply git patches from" >&2
+	exit 4
+fi
+tarball="$1"
+patchdir="$2"
+tarball_dir=${tarball%%.tar.gz}
+if ! [ -f "${tarball}" ] || [ "${tarball_dir}" = "${tarball}" ] ; then
+	echo "Tarball ${tarball} does not exist or is not in the format <file>.tar.gz " >&2
+	exit 4
+fi
 
-for p in /tmp/gitpatches/*; do
-#	if ! git am "${p}"; then
+if ! [ -d "${patchdir}" ]; then
+	echo "Patch directory ${patchdir} does not exist" >&2
+	exit 4
+fi
+
+rm -rf "${tarball_dir}"
+tar -xvf "${tarball}"
+if ! cd "${tarball_dir}"; then
+	echo "Extract of tarball ${tarball} did not create ${tarball_dir}" >&2
+	exit 4
+fi
+if ! git init || ! git add . || ! git commit -m "main" || ! git checkout -b openssl ; then
+	echo "Unable to initialize a git repository for the tarball" >&2 
+	exit 4
+fi
+
+for p in "${patchdir}"/*; do
 	if ! git apply "${p}"; then
+		echo "Unable to apply patch ${p} from ${patchdir}" >&2
 		break
 	fi
 done
