Perform shell formatting

diff --git a/bin/zopen-generate b/bin/zopen-generate
--- a/bin/zopen-generate
+++ b/bin/zopen-generate
@@ -6,14 +6,14 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename $0)
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -21,13 +21,13 @@ buildLicenseLookup()
 {
   licensesCSV="${MYDIR}/../data/licenses.csv"
   if [ ! -r "$licensesCSV" ]; then
-    return 4;
+    return 4
   fi
 
   validLicenseNames="$(cat $licensesCSV | tail +1 | cut -f1 -d',' | xargs)"
 }
 
-printSyntax() 
+printSyntax()
 {
   args=$*
   echo "zopen-generate will generate a zopen compatible project" >&2
@@ -47,7 +47,7 @@ if [[ $# -eq 1 ]]; then
     exit 8
   fi
 fi
- 
+
 buildLicenseLookup
 
 printHeader "Generate a zopen project"
@@ -110,7 +110,7 @@ mkdir -p ${name}port/patches
 
 # Create external LICENSE
 touch "${name}port/patches/LICENSE" && chtag -tc 819 "${name}port/patches/LICENSE"
-echo "${licenseName}\nView license contents at ${licenseUrl}" > "${name}port/patches/LICENSE"
+echo "${licenseName}\nView license contents at ${licenseUrl}" >"${name}port/patches/LICENSE"
 
 buildenv="${name}port/buildenv"
 touch $buildenv && chtag -tc 819 $buildenv
@@ -140,7 +140,6 @@ fi
 if [ ! -z "$runtimedeps" ]; then
   buildenvContents="${buildenvContents}export ZOPEN_RUNTIME_DEPS=\"$runtimedeps\"\n"
 fi
-
 
 buildenvContents="${buildenvContents}\nzopen_check_results()
 {
@@ -172,12 +171,12 @@ zopen_get_version()
   echo \"1.0.0\"
 }"
 
-/bin/echo "$buildenvContents" > $buildenv
+/bin/echo "$buildenvContents" >$buildenv
 
 printInfo "$buildenv created"
 
 touch "${name}port/README.md" && chtag -tc 819 "${name}port/README.md"
-cat <<EOT > "${name}port/README.md"
+cat <<EOT >"${name}port/README.md"
 ${name}
 
 ${description}
@@ -186,10 +185,10 @@ printInfo "${name}port/README.md created"
 
 createCICD()
 {
-buildline=$1
-touch "${name}port/cicd-$buildline.groovy" && chtag -tc 819 "${name}port/cicd-$buildline.groovy"
-buildlineUpper=$(echo "$buildline" | awk '{print toupper($0)}')
-cat <<EOT > "${name}port/cicd-$buildline.groovy"
+  buildline=$1
+  touch "${name}port/cicd-$buildline.groovy" && chtag -tc 819 "${name}port/cicd-$buildline.groovy"
+  buildlineUpper=$(echo "$buildline" | awk '{print toupper($0)}')
+  cat <<EOT >"${name}port/cicd-$buildline.groovy"
 node('linux')
 {
   stage ('Poll') {
@@ -211,7 +210,7 @@ createCICD "stable"
 createCICD "dev"
 
 touch "${name}port/.gitignore" && chtag -tc 819 "${name}port/.gitignore"
-cat <<EOT > "${name}port/.gitignore"
+cat <<EOT >"${name}port/.gitignore"
 log/
 log.DEV/
 log.STABLE/
