Correct shell scripts issues, format shell scripts

diff --git a/bin/zopen-compute-builddeps b/bin/zopen-compute-builddeps
--- a/bin/zopen-compute-builddeps
+++ b/bin/zopen-compute-builddeps
@@ -8,14 +8,14 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename "$0")
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -36,11 +36,11 @@ if [ $# -eq 0 ]; then
 fi
 
 if [[ $# -eq 1 ]]; then
-  if [ "x$1" = "x--help" ]; then
+  if [ "$1" = "--help" ]; then
     syntax
     exit 0
-  elif [ "x$1" = "x--version" ]; then
-    zopen --version $ME
+  elif [ "$1" = "--version" ]; then
+    zopen --version "${ME}"
     exit 0
   else
     echo "Unrecognized option $1. Processing terminated" >&2
@@ -53,7 +53,7 @@ rootpkg="$1"
 
 tmpdir="/tmp/blddep_$$"
 
-if ! mkdir "${tmpdir}" ; then
+if ! mkdir "${tmpdir}"; then
   echo "Unable to create temporary directory for computing transitive closure" >&2
   syntax
 fi
@@ -71,8 +71,8 @@ changed=true
 while ${changed}; do
   changed=false
   for pkg in ${deps}; do
-    if ! [[ -v scanned["${pkg}"] ]] ; then
-      if ! git clone "git@github.com:ZOSOpenTools/${pkg}port.git" ; then
+    if ! [[ -v scanned["${pkg}"] ]]; then
+      if ! git clone "git@github.com:ZOSOpenTools/${pkg}port.git"; then
         echo "Unable to clone package ${pkg}" >&2
         exit 4
       else
@@ -80,15 +80,15 @@ while ${changed}; do
         changed=true
       fi
       newpkgs=$(grep "ZOPEN_${primary_type}_DEPS" "${pkg}port/buildenv" | awk -F '"' '{print $2; }')
-      if [ "x${newpkgs}" = "x" ]; then
+      if [ "${newpkgs}" = "" ]; then
         # try again with secondary type
         newpkgs=$(grep "ZOPEN_${secondary_type}_DEPS" "${pkg}port/buildenv" | awk -F '"' '{print $2; }')
       fi
-      if $verbose; then
+      if ${verbose}; then
         echo "${pkg} needs ${newpkgs}"
       fi
       for newpkg in ${newpkgs}; do
-        if ! [[ -v scanned["${newpkg}"] ]] ; then
+        if ! [[ -v scanned["${newpkg}"] ]]; then
           deps="${deps} ${newpkg}"
         fi
       done
diff --git a/bin/zopen-remove b/bin/zopen-remove
--- a/bin/zopen-remove
+++ b/bin/zopen-remove
@@ -5,70 +5,71 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename "$0")
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
-printSyntax() 
+printSyntax()
 {
   args=$*
   echo "zopen remove is a utility to remove installed z/OS Open Tools packages."
   echo "Syntax: zopen remove [<option>]* <package, ...>" >&2
   echo "  where <option> may be one or more of:" >&2
-  echo "  --help: print this help"  >&2
-  echo "  --version: print version"  >&2
-  echo "  -p|--purge: remove package, the versioned directory and any cached file"  >&2
+  echo "  --help: print this help" >&2
+  echo "  --version: print version" >&2
+  echo "  -p|--purge: remove package, the versioned directory and any cached file" >&2
   echo "  -v: run in verbose mode" >&2
   echo "  and <package> is a list of one or more projects to uninstall" >&2
 }
 
-removePackages(){
+removePackages()
+{
   pkglist=$*
 
-  echo "$pkglist" | xargs | tr ' ' '\n' | sort | while read pkg; do
-    printHeader "Removing package: $pkg"
-    printInfo "- Checking status of package '$pkg'"
-    if [ ! -f $ZOPEN_PKGINSTALL/$pkg/$pkg/.active ]; then 
-      printInfo "${NC}${YELLOW}Package '$pkg' is not installed${NC}"
+  echo "${pkglist}" | xargs | tr ' ' '\n' | sort | while read pkg; do
+    printHeader "Removing package: ${pkg}"
+    printInfo "- Checking status of package '${pkg}'"
+    if [ ! -f "${ZOPEN_PKGINSTALL}"/"${pkg}"/"${pkg}"/.active ]; then
+      printInfo "${NC}${YELLOW}Package '${pkg}' is not installed${NC}"
     else
       printInfo "- Package installed, unmeshing from system"
       version="unknown"
-      if [ -e "${ZOPEN_PKGINSTALL}/${pkg}/$pkg/.releaseinfo" ]; then
-        version=$(cat "${ZOPEN_PKGINSTALL}/${pkg}/$pkg/.releaseinfo")
+      if [ -e "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}/.releaseinfo" ]; then
+        version=$(cat "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}/.releaseinfo")
       fi
 
-      if [ -e "$ZOPEN_PKGINSTALL/$pkg/$pkg" ]; then
-        deref=$(cd "$ZOPEN_PKGINSTALL/$pkg/$pkg" && pwd -P | awk -F/ '{ print $(NF)}')
-        installedlinksfile="$ZOPEN_PKGINSTALL/$pkg/$deref/.links"
-        if $purge; then
+      if [ -e "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}" ]; then
+        deref=$(cd "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}" && pwd -P | awk -F/ '{ print $(NF)}')
+        installedlinksfile="${ZOPEN_PKGINSTALL}/${pkg}/${deref}/.links"
+        if ${purge}; then
           printInfo "- Purging package"
           printVerbose "Checking if we are currently in a directory that is to be purged"
-          [ "${PWD##$ZOPEN_PKGINSTALL/$pkg/$pkg}" != "$PWD" ] && cd $ZOPEN_PKGINSTALL
-          rm -rf $(cd "$ZOPEN_PKGINSTALL/$pkg/$pkg" && pwd -P)
-          syslog $ZOPEN_LOG_PATH/audit.log $LOG_A "$CAT_PACKAGE,$CAT_REMOVE" "REMOVE" "removePackage" "Purging package:'${needle};version:$version;"
+          [ "${PWD##"${ZOPEN_PKGINSTALL}"/"${pkg}"/"${pkg}"}" != "${PWD}" ] && cd "${ZOPEN_PKGINSTALL}" || exit
+          rm -rf $(cd "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}" && pwd -P)
+          syslog "${ZOPEN_LOG_PATH}"/audit.log "${LOG_A}" "${CAT_PACKAGE},${CAT_REMOVE}" "REMOVE" "removePackage" "Purging package:'${needle};version:${version};"
         else
           printInfo "- Removing metadata file to mark uninstall"
-          rm -f "$ZOPEN_PKGINSTALL/$pkg/$pkg/.active"
+          rm -f "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}/.active"
           printInfo "- Breaking link from current to versioned"
-          rm -f "$ZOPEN_PKGINSTALL/$pkg/$pkg"
+          rm -f "${ZOPEN_PKGINSTALL}/${pkg}/${pkg}"
         fi
         printVerbose "Main symlink removed, removing dangling symlinks"
-        unsymlinkFromSystem "$pkg" "$ZOPEN_ROOTFS" "$installedlinksfile"
+        unsymlinkFromSystem "${pkg}" "${ZOPEN_ROOTFS}" "${installedlinksfile}"
       fi
 
       printInfo "- Removing profiled entry"
-      [ -d "$ZOPEN_ROOTFS/etc/profiled/$pkg" ] && rm -rf "$ZOPEN_ROOTFS/etc/profiled/$pkg"
+      [ -d "${ZOPEN_ROOTFS}/etc/profiled/${pkg}" ] && rm -rf "${ZOPEN_ROOTFS}/etc/profiled/${pkg}"
 
-      syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_PACKAGE,$CAT_REMOVE" "REMOVE" "removePackage" "Removed package:'${needle};version:$version;"
-      printInfo "${NC}${GREEN}Successfully removed: $pkg${NC}"
+      syslog "${ZOPEN_LOG_PATH}/audit.log" "${LOG_A}" "${CAT_PACKAGE},${CAT_REMOVE}" "REMOVE" "removePackage" "Removed package:'${needle};version:${version};"
+      printInfo "${NC}${GREEN}Successfully removed: ${pkg}${NC}"
     fi
   done
 }
@@ -81,28 +82,28 @@ purge=false
 chosenRepos=""
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    "-p" | "--purge")
-      purge=true
-      ;;
-    "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
-      printSyntax "${args}"
-      exit 0
-      ;;
-    "--version")
-      zopen --version $ME
-      exit 0
-      ;;
-    "-v" | "--v" | "-verbose" | "--verbose")
-      verbose=true
-      ;;
-    *)
-      chosenRepos="$chosenRepos $1";
-      ;;
+  "-p" | "--purge")
+    purge=true
+    ;;
+  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
+    printSyntax "${args}"
+    exit 0
+    ;;
+  "--version")
+    zopen --version "${ME}"
+    exit 0
+    ;;
+  "-v" | "--v" | "-verbose" | "--verbose")
+    verbose=true
+    ;;
+  *)
+    chosenRepos="${chosenRepos} $1"
+    ;;
   esac
-  shift;
+  shift
 done
 
-[[ ! -z "$chosenRepos" ]] || printError "No packages selected for removal" 
+[[ ! -z "${chosenRepos}" ]] || printError "No packages selected for removal"
 mutexReq "zopen" "zopen"
-removePackages "$chosenRepos"
+removePackages "${chosenRepos}"
 mutexFree "zopen"
diff --git a/bin/zopen-split-patch b/bin/zopen-split-patch
--- a/bin/zopen-split-patch
+++ b/bin/zopen-split-patch
@@ -4,14 +4,14 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename "$0")
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -22,11 +22,11 @@ printSyntax()
   printf "Syntax: %s [<patch file>]\n" "${0}" >&2
 }
 
-if [ "x$1" = "x--help" ]; then
+if [ "$1" = "--help" ]; then
   printSyntax
   exit 0
-elif [ "x$1" = "x--version" ]; then
-  zopen --version $ME
+elif [ "$1" = "--version" ]; then
+  zopen --version "${ME}"
   exit 0
 fi
 
@@ -34,12 +34,12 @@ if [ $# -lt 1 ]; then
   exit 4
 fi
 
-if ! mkdir -p "${pd}" ; then
+if ! mkdir -p "${pd}"; then
   printf 'Unable to create patch directory: %s. No patch files created\n' "${pd}" >&2
   exit 8
 fi
 
-for aggregate in $@ ; do
+for aggregate in $@; do
   info=$(grep -n '^diff --git' "${aggregate}")
   lastline=$(wc -l "$1" | awk '{ print $1; }')
   lines=$(printf "%s" "${info}" | awk -F: ' { print $1; }')
@@ -60,20 +60,20 @@ for aggregate in $@ ; do
       af="${file[i]}.patch"
       d=$(dirname "${af}")
       rf=$(basename "${af}")
-      if ! mkdir -p "${pd}/${d}" ; then
+      if ! mkdir -p "${pd}/${d}"; then
         printf 'Unable to create directory %s. Partial splitting has been performed under %s', "${d}" "${pd}" >&2
         exit 8
       fi
       #printf "%s/%s/%s %d %d\n" "${pd}" "${d}" "${rf}" "${start}" "${end}"
-      taillines=$((end-start))
-      headlines=$((end-1))
+      taillines=$((end - start))
+      headlines=$((end - 1))
       content=$(head -n "${headlines}" "${aggregate}" | tail -n "${taillines}")
-      if ! printf '%s\n' "${content}" >"${pd}/${d}/${rf}" ; then
+      if ! printf '%s\n' "${content}" >"${pd}/${d}/${rf}"; then
         printf 'Unable to write patch file to %s. Partial splitting has been performed under %s', "${pd}/${d}/${rf}" "${pd}" >&2
         exit 8
       fi
     fi
     start="${end}"
-    i=$((i+1))
+    i=$((i + 1))
   done
 done
