Implement install from pax Merge shfmt changes, ensure var encapsulation in ${...} Resolve some shellcheck issues

diff --git a/bin/zopen-init b/bin/zopen-init
--- a/bin/zopen-init
+++ b/bin/zopen-init
@@ -12,14 +12,15 @@ ZOPEN_DONT_PROCESS_CONFIG=1
 #
 setupMyself()
 {
-        ME=$(basename "$0")
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename "$0")
+  MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  # shellcheck source=/dev/null
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
@@ -110,7 +111,7 @@ while [ $# -gt 0 ]; do
     "--paxrepodir")
       shift
       paxrepodir="$1" # Only support single repo directory
-    ;;
+      ;;
     "-h" | "--help" | "-?")
       printHelp
       exit 0
@@ -279,9 +280,9 @@ else
   releaseLine="STABLE"
   printInfo "- Configured zopen to use stable releaseline packages"
 fi
-echo "$releaseLine" > "$rootfs/etc/zopen/releaseline"
-if [ -n "$paxrepodir" ]; then
-  echo "dir:$paxrepodir" > "$rootfs/etc/zopen/paxrepodir"
+echo "${releaseLine}" > "${rootfs}/etc/zopen/releaseline"
+if [ -n "${paxrepodir}" ]; then
+  echo "dir:${paxrepodir}" > "${rootfs}/etc/zopen/paxrepodir"
 fi
 printInfo "- Check for shipped curl pax"
 curlpax="packages/curl-8.4.0.20231011_155722.zos.pax.Z"
diff --git a/bin/zopen-upgrade b/bin/zopen-upgrade
--- a/bin/zopen-upgrade
+++ b/bin/zopen-upgrade
@@ -58,16 +58,7 @@ Report bugs at https://github.com/ZOSOpenTools/meta/issues .
 HELPDOC
 }
 
-upgradePackages()( # Note the subshell '()'
-  packages="$1"
-  printDebug "Packages to upgrade: $packages"
-  sessionList="" # Track the packages installed during this session to prevent repeats
-  mutexReq "zopen" "zopen"
-  for pkg in $packages; do
-    handlePackageInstall "$pkg"
-  done
-  mutexFree "zopen"
-)
+
 
 # Main code start here
 # Need to set a number of variables for use in the install function
@@ -128,17 +119,17 @@ while [ $# -gt 0 ]; do
       xdebug=true
     ;;
     "--version")
-      zopen --version $ME
+      zopen --version "${ME}"
       exit 0
       ;;
     *)
-      chosenRepos=" $chosenRepos $1 ";
+      chosenRepos=" ${chosenRepos} $1 ";
       ;;
   esac
   shift;
 done
 
-$xdebug && set -x && printVerbose "Enabled command execution trace" 
+${xdebug} && set -x && printVerbose "Enabled command execution trace" 
 
 if [ -z "${chosenRepos}" ]; then
 
@@ -146,10 +137,10 @@ if [ -z "${chosenRepos}" ]; then
     printInfo "- Querying for installed packages"
     progressHandler "spinner" "- Query complete" &
     ph=$!
-    killph="kill -HUP $ph"
-    addCleanupTrapCmd "$killph"
+    killph="kill -HUP ${ph} 2>/dev/null"
+    addCleanupTrapCmd "${killph}"
     chosenRepos="$(${MYDIR}/zopen-query list --installed --no-header --no-versions)"
-    $killph 2>/dev/null  # if the timer is not running, the kill will fail
+    ${killph} # if the timer is not running, the kill will fail
 fi
 
 checkIfConfigLoaded
@@ -158,57 +149,63 @@ export SSL_CERT_FILE="${ZOPEN_CA}"
 export GIT_SSL_CAINFO="${ZOPEN_CA}"
 export CURL_CA_BUNDLE="${ZOPEN_CA}"
 
-printDebug "Installing to zopen file system: $ZOPEN_ROOTFS"
-if [ -z "$ZOPEN_ROOTFS" ]; then
-  printError "Unable to locate zopen file system, \$ZOPEN_ROOTFS is undefined"
+printDebug "Installing to zopen file system: ${ZOPEN_ROOTFS}"
+if [ -z "${ZOPEN_ROOTFS}" ]; then
+  printError "Unable to locate zopen file system, \${ZOPEN_ROOTFS} is undefined"
 fi
-downloadDir="$ZOPEN_ROOTFS/var/cache/zopen"
+downloadDir="${ZOPEN_ROOTFS}/var/cache/zopen"
 
 
 if [ ! -d "${downloadDir}" ]; then
   mkdir -p "${downloadDir}"
   if [ $? -gt 0 ]; then
-    printError "Could not create download directory: $downloadDir"
+    printError "Could not create download directory: ${downloadDir}"
   fi
 fi
 
-printDebug "Checking if installing from pax files: $paxinstall"
-if ! $paxinstall; then
+printDebug "Checking if installing from pax files: ${paxinstall}"
+if ! ${paxinstall}; then
   # Parse passed in repositories and check if valid zopen framework repos
   printVerbose "Querying remote repo for latest package information"
   getReposFromGithub
   grfgRc=$?
-  $killph 2>/dev/null  # if the timer is not running, the kill will fail
-  [ 0 -ne $grfgRc ] && exit $grfgRc;
+  ${killph} # if the timer is not running, the kill will fail
+  [ 0 -ne ${grfgRc} ] && exit ${grfgRc};
 else
   printDebug "Using pax files for install, not GH"
-  [ -n "$paxrepodir" ] && printDebug "Using '$paxrepodir' to locate pax files"
+  [ -n "${paxrepodir}" ] && printDebug "Using '${paxrepodir}' to locate pax files"
 fi
 installArray=""
 
-if $paxinstall; then
-  printDebug "Installing from pax files as listed in arguments: '$chosenRepos'"
-  installArray="$chosenRepos"
+if ${paxinstall}; then
+  printDebug "Installing from pax files as listed in arguments: '${chosenRepos}'"
+  installArray="${chosenRepos}"
 else
   printDebug "Parsing list of packages to install and verifying validity"
 
   badportlist=""
   for chosenRepo in $(echo "${chosenRepos}" | tr ',' ' '); do
-    printVerbose "Processing repo: $chosenRepo"
+    printVerbose "Processing repo: ${chosenRepo}"
     printDebug "Stripping any version (%), tag (#) or port suffixes and trim"
-    toolrepo=$(echo "$chosenRepo" | sed -e 's#%.*##' -e 's#=.*##' -e 's#.*port##')
+    toolrepo=$(echo "${chosenRepo}" | sed -e 's#%.*##' -e 's#=.*##' -e 's#.*port##')
 
-    toolfound=$(echo "${repo_results}" | awk -vtoolrepo="$toolrepo" '$0 == toolrepo {print}') 
-    if [ "$toolfound" = "$toolrepo" ]; then
-      printVerbose "Adding '$chosenRepo' to the install queue"
-      installArray=$(printf "%s\n%s" "$installArray" "$chosenRepo")
+    toolfound=$(echo "${repo_results}" | awk -vtoolrepo="${toolrepo}" '$0 == toolrepo {print}') 
+    if [ "${toolfound}" = "${toolrepo}" ]; then
+      printVerbose "Adding '${chosenRepo}' to the install queue"
+      installArray=$(printf "%s\n%s" "${installArray}" "${chosenRepo}")
     else
-      badportlist=$(printf "%s %s" "$badportlist" "$toolrepo")
+      badportlist=$(printf "%s %s" "${badportlist}" "${toolrepo}")
     fi
   done
-  if [ -n "$badportlist" ]; then
-    printError "The following requested port(s) do not exist:\n\t$badportlist"
+  if [ -n "${badportlist}" ]; then
+    printError "The following requested port(s) do not exist:\n\t${badportlist}"
   fi
 fi
 
-upgradePackages "$installArray"
+printDebug "Packages to upgrade: ${installArray}"
+sessionList="" # Track the packages installed during this session to prevent repeats
+mutexReq "zopen" "zopen"
+for pkg in ${installArray}; do
+  handlePackageInstall "${pkg}"
+done
+mutexFree "zopen"
