move code from lib up to either bin or include

diff --git a/bin/zopen b/bin/zopen
--- a/bin/zopen
+++ b/bin/zopen
@@ -2,7 +2,22 @@
 #
 # General purpose zopen script
 #
-ME=$(basename $0)
+ZOPEN_DONT_PROCESS_CONFIG=1 
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 printSyntax()
 {
@@ -44,11 +59,7 @@ printHelp()
   echo " zopen generate" >&2
 }
 
-export bindir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-
-export PATH="${bindir}:${PATH}"
-ZOPEN_DONT_PROCESS_CONFIG=1
-. "${bindir}/lib/common.inc"
+export PATH="${MYDIR}:${PATH}"
 
 args=$*
 legacy=false
@@ -60,23 +71,23 @@ while [[ $# -gt 0 ]]; do
     ;;
     "alt")
       shift
-      exec "${bindir}/lib/zopen-alt" $@
+      exec "${MYDIR}/lib/zopen-alt" $@
       ;;
     "build")
       shift
-      exec "${bindir}/lib/zopen-build" $@
+      exec "${MYDIR}/lib/zopen-build" $@
       ;;
     "clean")
       shift
-      exec "${bindir}/lib/zopen-clean" $@
+      exec "${MYDIR}/lib/zopen-clean" $@
       ;;
     "download")
       shift
-      exec "${bindir}/lib/zopen-install" $@
+      exec "${MYDIR}/lib/zopen-install" $@
       ;;
     "generate")
       shift
-      exec "${bindir}/lib/zopen-generate" $@
+      exec "${MYDIR}/lib/zopen-generate" $@
       ;;
     "help" | "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
       printHelp "${args}"
@@ -85,38 +96,38 @@ while [[ $# -gt 0 ]]; do
     "init")
       shift
       if $legacy; then
-        exec "${bindir}/lib/zopen-init --legacy" $@
+        exec "${MYDIR}/lib/zopen-init --legacy" $@
       else
-        exec "${bindir}/lib/zopen-init" $@
+        exec "${MYDIR}/lib/zopen-init" $@
       fi
       ;;
     "install" | "-i")
       shift
-      exec "${bindir}/lib/zopen-install" $@
+      exec "${MYDIR}/lib/zopen-install" $@
       ;;
     "list" | "-l")
       shift
-      exec "${bindir}/lib/zopen-query" "--list" $@
+      exec "${MYDIR}/lib/zopen-query" "--list" $@
       ;;
     "query" | "-q")
       shift
-      exec "${bindir}/lib/zopen-query" $@
+      exec "${MYDIR}/lib/zopen-query" $@
       ;;
     "remove" | "-r" | "uninstall" | "un" | "erase" | "e")
       shift
-      exec "${bindir}/lib/zopen-remove" $@
+      exec "${MYDIR}/lib/zopen-remove" $@
       ;;
     "search" | "-s")
       shift
-      exec "${bindir}/lib/zopen-query" --remote-search $@
+      exec "${MYDIR}/lib/zopen-query" --remote-search $@
       ;;
     "update-cacert")
       shift
-      exec "${bindir}/lib/zopen-update-cacert" $@
+      exec "${MYDIR}/lib/zopen-update-cacert" $@
       ;;
     "upgrade" | "up")
       shift
-      exec "${bindir}/lib/zopen-install" -u $@
+      exec "${MYDIR}/lib/zopen-install" -u $@
       ;;
     "--version")
       if [ "x$2" = "x" ]; then
@@ -124,7 +135,7 @@ while [[ $# -gt 0 ]]; do
       else
         name="$2"
       fi
-      exec "${bindir}/lib/zopen-version" $name 
+      exec "${MYDIR}/lib/zopen-version" $name 
       ;;
     *)
       printSoftError "Unknown option ${1} specified"
diff --git a/bin/zopen-generate b/bin/zopen-generate
--- a/bin/zopen-generate
+++ b/bin/zopen-generate
@@ -1,14 +1,25 @@
 #!/bin/sh
 # Generates a zopen compatible project
-ME=$(basename $0)
-
-export utildir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-
-. "${utildir}/common.inc"
+#
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 buildLicenseLookup()
 {
-  licensesCSV="${utildir}/../data/licenses.csv"
+  licensesCSV="${MYDIR}/../data/licenses.csv"
   if [ ! -r "$licensesCSV" ]; then
     return 4;
   fi
@@ -104,7 +115,7 @@ echo "${licenseName}\nView license contents at ${licenseUrl}" > "${name}port/pat
 buildenv="${name}port/buildenv"
 touch $buildenv && chtag -tc 819 $buildenv
 
-cp "${utildir}/../data/CONTRIBUTING.md" "${name}port/CONTRIBUTING.md"
+cp "${MYDIR}/../data/CONTRIBUTING.md" "${name}port/CONTRIBUTING.md"
 
 if [ ! -z "$stablePath" ]; then
   buildenvContents="export ZOPEN_STABLE_URL=\"$stablePath\"\n"
@@ -209,12 +220,12 @@ install/
 EOT
 printInfo "${name}port/.gitignore created"
 
-if [ -e "${utildir}/../../LICENSE" ]; then
-  cp "${utildir}/../../LICENSE" "${name}port/LICENSE"
+if [ -e "${MYDIR}/../../LICENSE" ]; then
+  cp "${MYDIR}/../../LICENSE" "${name}port/LICENSE"
 elif [ -n "$ZOPEN_ROOTFS" ]; then
   pkgInstallDir="$(cat "$ZOPEN_ROOTFS/etc/zopen/fstype")"
-  if [ -e "${utildir}/../../../$pkgInstallDir/meta/meta/LICENSE" ]; then
-    cp "${utildir}/../../../$pkgInstallDir/meta/meta/LICENSE" "${name}port/LICENSE"
+  if [ -e "${MYDIR}/../../../$pkgInstallDir/meta/meta/LICENSE" ]; then
+    cp "${MYDIR}/../../../$pkgInstallDir/meta/meta/LICENSE" "${name}port/LICENSE"
   else
     printError "Could not locate LICENSE file to copy for project"
   fi
diff --git a/bin/zopen-help2man b/bin/zopen-help2man
--- a/bin/zopen-help2man
+++ b/bin/zopen-help2man
@@ -1,5 +1,19 @@
 #!/bin/sh
-ME=$(basename $0)
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 #
 # Routine to generate man pages from the --help and --version for the various tools
@@ -31,8 +45,7 @@ else
 fi
 
 set -e
-export mydir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-export rootdir="$( cd "$mydir/../../" && dirname "$PWD" >/dev/null 2>&1 && pwd -P )"
+export rootdir="$( cd "$MYDIR/../../" && dirname "$PWD" >/dev/null 2>&1 && pwd -P )"
 
 help2manopts="--no-discard-stderr -N"
 
@@ -42,7 +55,7 @@ if ! [ -d "${mandir}" ]; then
   exit 8
 fi
 
-if [ "x${mydir}" = "x" ] || [ "x${rootdir}" = "x" ]; then
+if [ "x${MYDIR}" = "x" ] || [ "x${rootdir}" = "x" ]; then
   echo "Internal error. Unable to determine version information" >&2
   exit 8
 fi
diff --git a/bin/zopen-md2man b/bin/zopen-md2man
--- a/bin/zopen-md2man
+++ b/bin/zopen-md2man
@@ -1,7 +1,22 @@
 #!/bin/sh
 # Generate man1/xxx.1.gz from xxx.md
 # Probably throw-away since we are going to use help2man instead
-ME=$(basename $0)
+#
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 printSyntax()
 {
@@ -26,9 +41,8 @@ fi
 set -e
 zopen_version='0.7.0' ## add code to perform zopen --version once supported
 zopen_date=$(date "+%B %d %Y")
-curdir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
 
-mandir="${curdir}/man1" ## may want this elsewhere
+mandir="${MYDIR}/man1" ## may want this elsewhere
 
 for mdf in "${curdir}"/*.md; do
 	bf=$(basename $mdf)
diff --git a/bin/zopen-migrate-buildenv b/bin/zopen-migrate-buildenv
--- a/bin/zopen-migrate-buildenv
+++ b/bin/zopen-migrate-buildenv
@@ -3,6 +3,22 @@
 # simple sed script to change over env vars in a buildenv from 'old style' to 'new style'
 # By no means bullet-proof but might save some typing
 #
+##
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
+
 sed -i 's/ZOPEN_TARBALL/ZOPEN_STABLE/' buildenv
 sed -i 's/ZOPEN_GIT/ZOPEN_DEV/' buildenv
 sed -i 's/ZOPEN_TYPE/ZOPEN_BUILD_LINE/' buildenv
diff --git a/bin/zopen-migrate-groovy b/bin/zopen-migrate-groovy
--- a/bin/zopen-migrate-groovy
+++ b/bin/zopen-migrate-groovy
@@ -5,6 +5,22 @@
 # Has no checks in it and requires you fill in the ...'s in the generated files.
 # Also, spacing is a bit off - but easy enough to change post-processing in the editor.
 #
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
+
 class=$(cat cicd.groovy | grep "class: ")
 branches=$(cat cicd.groovy | grep "branches: ")
 url=$(cat cicd.groovy | grep "userRemoteConfigs")
diff --git a/bin/zopen-query b/bin/zopen-query
--- a/bin/zopen-query
+++ b/bin/zopen-query
@@ -1,10 +1,20 @@
 #!/bin/sh
 # Query utility for z/OS Open Tools - https://github.com/ZOSOpenTools
-ME=$(basename $0)
-
-export utildir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-
-. "${utildir}/common.inc"
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 printSyntax() 
 {
diff --git a/bin/zopen-update-cacert b/bin/zopen-update-cacert
--- a/bin/zopen-update-cacert
+++ b/bin/zopen-update-cacert
@@ -2,15 +2,21 @@
 #
 # Updates the cacert in zopen meta root directory
 #
-ME=$(basename $0)
-
-if [ -z "$utildir" ]; then
-  export mydir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-else
-  mydir="$utildir"
-fi
-
-. "${mydir}/common.inc"
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 # Temporary files
 for tmp in "$TMPDIR" "$TMP" /tmp
@@ -81,11 +87,8 @@ updateCACert()
 }
 
 # Main code start here
-export mydir="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-
-. "${mydir}/common.inc"
 verbose=false
-export default_dir="$( cd "${mydir}/../../" && pwd -P )"
+export default_dir="$( cd "${MYDIR}/../" && pwd -P )"
 export cacert_update_url="https://curl.se/ca/cacert.pem"
 
 # Temporary files
diff --git a/bin/zopen-versions b/bin/zopen-versions
--- a/bin/zopen-versions
+++ b/bin/zopen-versions
@@ -1,5 +1,19 @@
 #!/bin/env bash
-ME=$(basename $0)
+#
+# All zopen-* scripts MUST start with this code to maintain consistency
+#
+setupMyself()
+{
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
+}
+setupMyself
 
 #
 # Print out installed version of z/OS tool and corresponding BREW latest version
