Revert "Correct shell scripts issues, format shell scripts"
This reverts commit 39ad0130e520f2f7dfe42bed8a9f1018974660b8.

diff --git a/bin/zopen-help2man b/bin/zopen-help2man
--- a/bin/zopen-help2man
+++ b/bin/zopen-help2man
@@ -4,14 +4,14 @@
 #
 setupMyself()
 {
-  ME=$(basename "$0")
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -23,29 +23,29 @@ setupMyself
 
 printSyntax()
 {
-  echo "${ME} will generate man pages from help and version information for zopen and zopen-* tools" >&2
-  echo "Syntax: ${ME} DIRECTORY" >&2
+  echo "$ME will generate man pages from help and version information for zopen and zopen-* tools" >&2
+  echo "Syntax: $ME DIRECTORY" >&2
   echo "  where DIRECTORY is the directory to write the man pages to (the directory needs to already exist)" >&2
 }
 
 if [[ $# -eq 1 ]]; then
-  if [ "$1" = "--help" ]; then
+  if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
-  elif [ "$1" = "--version" ]; then
-    zopen --version "${ME}"
+  elif [ "x$1" = "x--version" ]; then
+    zopen --version $ME
     exit 0
   else
     mandir="$1"
   fi
 else
-  echo "Expected one parameter to be passed to ${ME}. $# were passed in. No action performed" >&2
+  echo "Expected one parameter to be passed to $ME. $# were passed in. No action performed" >&2
   printSyntax
   exit 8
 fi
 
 set -e
-export rootdir="$(cd "${MYDIR}/../" && dirname "${PWD}" >/dev/null 2>&1 && pwd -P)"
+export rootdir="$( cd "$MYDIR/../" && dirname "$PWD" >/dev/null 2>&1 && pwd -P )"
 
 help2manopts="--no-discard-stderr -N"
 
@@ -55,7 +55,7 @@ if ! [ -d "${mandir}" ]; then
   exit 8
 fi
 
-if [ "${MYDIR}" = "" ] || [ "${rootdir}" = "" ]; then
+if [ "x${MYDIR}" = "x" ] || [ "x${rootdir}" = "x" ]; then
   echo "Internal error. Unable to determine version information" >&2
   exit 8
 fi
@@ -64,23 +64,26 @@ tooldirs="${rootdir}/bin"
 
 echo "Man pages will be written to: ${mandir}"
 for tooldir in ${tooldirs}; do
-  for tool in ${tooldir}/zopen*; do
-    basetool=$(basename "${tool}")
-    help2man "${help2manopts}" "${tool}" >"${mandir}/${basetool}.1"
-    if $("${tool}" --help >/dev/null 2>&1); then
+  for tool in $tooldir/zopen*; do
+    basetool=$(basename ${tool})
+    help2man ${help2manopts} "${tool}" >"${mandir}/${basetool}.1"
+    if  $( "${tool}" --help >/dev/null 2>&1 ) ; then
       # Tool has implemented --help
-      if $("${tool}" --version >/dev/null 2>&1); then
+      if  $( "${tool}" --version >/dev/null 2>&1 ) ; then
         echo "${basetool}"
-      else
+      else 
         echo "${tool} supports --help but not --version options. man page generation skipped." >&2
       fi
-    else
+    else 
       # Tool has NOT implemented --help
-      if $("${tool}" --version >/dev/null 2>&1); then
+      if  $( "${tool}" --version >/dev/null 2>&1 ) ; then
         echo "${tool} does not support --help but does support man page generation skipped." >&2
-      else
+      else 
         echo "${tool} does not support --help nor --version options. man page generation skipped." >&2
       fi
     fi
   done
 done
+
+
+
diff --git a/bin/zopen-md2man b/bin/zopen-md2man
--- a/bin/zopen-md2man
+++ b/bin/zopen-md2man
@@ -7,14 +7,14 @@
 #
 setupMyself()
 {
-  ME=$(basename "$0")
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -25,11 +25,11 @@ printSyntax()
 }
 
 if [[ $# -eq 1 ]]; then
-  if [ "$1" = "--help" ]; then
+  if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
-  elif [ "$1" = "--version" ]; then
-    zopen --version "${ME}"
+  elif [ "x$1" = "x--version" ]; then
+    zopen --version $ME
     exit 0
   else
     echo "Unrecognized option $1. Processing terminated" >&2
@@ -45,10 +45,10 @@ zopen_date=$(date "+%B %d %Y")
 mandir="${MYDIR}/man1" ## may want this elsewhere
 
 for mdf in "${curdir}"/*.md; do
-  bf=$(basename "${mdf}")
-  zopen_tool=${bf%%.md}
+	bf=$(basename $mdf)
+	zopen_tool=${bf%%.md}
 
-  header="---
+header="---
 title: ${zopen_tool}
 section: 1
 header: User Manual
@@ -56,7 +56,7 @@ footer: ${zopen_version}
 date: ${zopen_date}
 ---
 "
-  body=$(cat "${mdf}")
-  manfile="${mandir}/${zopen_tool}.1.gz"
-  echo "${header}${body}" | pandoc -s -f markdown -t man | gzip >"${manfile}"
+	body=$(cat ${mdf})
+	manfile="${mandir}/${zopen_tool}.1.gz"
+	echo "${header}${body}" | pandoc -s -f markdown -t man | gzip >${manfile}
 done
diff --git a/bin/zopen-version b/bin/zopen-version
--- a/bin/zopen-version
+++ b/bin/zopen-version
@@ -4,22 +4,22 @@
 #
 setupMyself()
 {
-  ME=$(basename "$0")
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
 printSyntax()
 {
-  echo "${ME} prints version information for ${package}"
-  echo "Usage: ${ME} [OPTION] tool"
-  echo "   or: ${ME} [OPTION]"
+  echo "$ME prints version information for ${package}"
+  echo "Usage: $ME [OPTION] tool"
+  echo "   or: $ME [OPTION]"
   echo "Syntax: zopen-version [OPTIONS]"
   echo "where OPTIONS can be:"
   echo "  --help: print this help"
@@ -35,10 +35,10 @@ warranty="There is NO WARRANTY, to the extent permitted by law."
 authors="Written by contributors to the z/OS Open Tools Community <https://github.com/ZOSOpenTools/meta/graphs/contributors>."
 
 if [[ $# -eq 1 ]]; then
-  if [ "$1" = "--help" ]; then
+  if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
-  elif [ "$1" = "--version" ]; then
+  elif [ "x$1" = "x--version" ]; then
     : # fall-through
   else
     tool="$1"
diff --git a/bin/zopen-versions b/bin/zopen-versions
--- a/bin/zopen-versions
+++ b/bin/zopen-versions
@@ -4,14 +4,14 @@
 #
 setupMyself()
 {
-  ME=$(basename "$0")
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -27,11 +27,11 @@ syntax()
 }
 
 if [[ $# -eq 1 ]]; then
-  if [ "$1" = "--help" ]; then
+  if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
-  elif [ "$1" = "--version" ]; then
-    zopen --version "${ME}"
+  elif [ "x$1" = "x--version" ]; then
+    zopen --version $ME
     exit 0
   else
     echo "Unrecognized option $1. Processing terminated" >&2
@@ -41,17 +41,17 @@ if [[ $# -eq 1 ]]; then
 fi
 
 if [ $# -eq 0 ]; then
-  root="${HOME}/zopen/prod"
+  root="$HOME/zopen/prod"
 else
   root="$1"
 fi
 
 if [ -d "${root}" ]; then
   echo "Using ${root} for determining z/OS tarball versions" >&2
-else
-  if [ "${root}" = "-?" ] || [ "${root}" = "-help" ]; then
+else 
+  if [ "x${root}" = "x-?" ] || [ "x${root}" = "x-help" ]; then
     :
-  else
+  else 
     echo "Unable to find ${root} for determining z/OS tarball versions" >&2
   fi
   syntax
@@ -73,18 +73,19 @@ brew_version_info=$(curl https://formulae.brew.sh/formula/ 2>/dev/null | grep '<
 for rawtool in ${tools}; do
   tool=${rawtool%%port}
   version_file=$(echo "${version_files}" | grep "${tool}-" | head -n 1)
-  if [ "${version_file}" = "" ]; then
+  if [ "x${version_file}" = "x" ]; then
     :
     #echo "No version file for ${tool}. ${tool} skipped" >&2
   else
-    version="$(cat "${version_file}")"
+    version="$(cat ${version_file})"
     brew_line=$(echo "${brew_version_info}" | grep -n ">${tool}<" | awk -F: '{print $1}')
-    if [ "${brew_line}" = "" ]; then
+    if [ "x${brew_line}" = "x" ]; then
       brew_version="unknown"
     else
-      next_brew_line=$((brew_line + 1))
+      next_brew_line=$((brew_line+1))
       brew_version=$(echo "${brew_version_info}" | sed -n "${next_brew_line}p" | awk -F '<|>' '{print $3}')
     fi
     echo "${tool} zos-version ${version} brew-version ${brew_version}"
   fi
 done
+
