Add copyright text (#642)
* Sort command line arguments

* Speed up help text printing

* Wrap help text at 80 columns

* Sort "see also" text

* Remove undocumented args

* Fix broken arg error message

* Remove period trailing bug link

* Add whitespace in help text

* Document -i argument

* Improve version message formatting

* Sort build envars

* Remove copyright text.

* Update license link.

diff --git a/bin/zopen b/bin/zopen
--- a/bin/zopen
+++ b/bin/zopen
@@ -1,11 +1,11 @@
 #!/bin/sh
 #
 # zopen wrapper script to allow single point of entry to zopen
-# tooling
+# tooling.
 #
 ZOPEN_DONT_PROCESS_CONFIG=1
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -13,7 +13,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -28,43 +28,43 @@ ${ME} is a utility for managing a z/OS Open Tools environment.
 Usage: ${ME} [COMMAND] [OPTION] [PARAMETERS]...
 
 Command:
-  init              initializes a zopen environment at the specified location
-  install           installs one or more z/OS Open Tools packages
-  list              lists information about z/OS Open Tools packages
-  upgrade           upgrades existing z/OS Open Tools packages
-  remove            removes installed z/OS Open Tools packages
-  build             builds the enclosing z/OS Open Tools git-cloned package
-  alt               manage alternate versions of z/OS Open Tools packages
-  clean             cleans up your zopen environment
-  query             list local or remote information about z/OS Open Tools packages
-  generate          generates a new zopen project
-  update-cacert     update the cacert.pem file used by z/OS Open Tools
+  alt               manage alternate versions of z/OS Open Tools packages.
+  build             builds the enclosing z/OS Open Tools git-cloned package.
+  clean             cleans up your zopen environment.
+  generate          generates a new zopen project.
+  init              initializes a zopen environment at the specified location.
+  install           installs one or more z/OS Open Tools packages.
+  list              lists information about z/OS Open Tools packages.
+  query             list local or remote info about z/OS Open Tools packages.
+  remove            removes installed z/OS Open Tools packages.
+  update-cacert     update the cacert.pem file used by z/OS Open Tools.
+  upgrade           upgrades existing z/OS Open Tools packages.
 
-Option:
-  -v, --verbose     run in verbose mode
-  -h,-?, --help     display this help and exit
+Options:
+  -h, --help, -?    display this help and exit.
+  -v, --verbose     run in verbose mode.
 
 Examples:
-  zopen --help      displays zopen help
-  zopen --version   displays the installed zopen version
-  zopen install git install the latest z/OS Open Tools git package
-  zopen upgrade -y  upgrade all installed packages to the latest release, without prompting
-  zopen alt bash    list the installed alternative bash z/OS Open Tools packages
+  zopen --help      displays zopen help.
+  zopen --version   displays the installed zopen version.
+  zopen install git install the latest z/OS Open Tools git package.
+  zopen upgrade -y  upgrade all installed packages to the latest release,
+                    without prompting.
+  zopen alt bash    list installed alternative bash z/OS Open Tools packages.
 
 SEE ALSO:
-  zopen-version(1)
+  zopen-alt(1)
+  zopen-build(1)
+  zopen-clean(1)
+  zopen-generate(1)
   zopen-init(1)
   zopen-install(1)
   zopen-query(1)
   zopen-remove(1)
-  zopen-build(1)
-  zopen-alt(1)
-  zopen-clean(1)
-  zopen-generate(1)
   zopen-update-cacert(1)
+  zopen-version(1)
 
-
-Report bugs at https://github.com/ZOSOpenTools/meta/issues .
+Report bugs at https://github.com/ZOSOpenTools/meta/issues
 
 HELPDOC
 }
diff --git a/bin/zopen-alt b/bin/zopen-alt
--- a/bin/zopen-alt
+++ b/bin/zopen-alt
@@ -1,7 +1,10 @@
 #!/bin/sh
+#
 # "Alternatives" utility for z/OS Open Tools - https://github.com/ZOSOpenTools
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+
+#
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -9,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -20,18 +23,18 @@ checkWritable
 printHelp()
 {
   cat << HELPDOC
-zopen alt is a utility for z/OS Open Tools to switch package versions 
+${ME} is a utility for z/OS Open Tools to switch package versions
 for currently installed packages.
 
-Usage: zopen alt [OPTION] [PACKAGE] [PARAMETERS]...
+Usage: ${ME} [OPTION] [PACKAGE] [PARAMETERS]...
 
 Options:
+  -h, --help, -?    display this help and exit.
+  --select [PACKAGE]
+                    select the active version for PACKAGE from a list.
   -s, --set [PACKAGE] [VERSION]
-                    set the active version for PACKAGE to VERSION 
-      --select [PACKAGE] 
-                    select the active version for PACKAGE from a list
-  -v, --verbose     run in verbose mode
-  -h,-?, --help     display this help and exit
+                    set the active version for PACKAGE to VERSION.
+  -v, --verbose     run in verbose mode.
   --version         print version
 
 Examples:
@@ -43,7 +46,7 @@ Examples:
                     set the active version of package 'foo' to version
                     foo-1.2.3.19700101_012345.zos if available
 
-Report bugs at https://github.com/ZOSOpenTools/meta/issues .
+Report bugs at https://github.com/ZOSOpenTools/meta/issues
 
 HELPDOC
 }
diff --git a/bin/zopen-clean b/bin/zopen-clean
--- a/bin/zopen-clean
+++ b/bin/zopen-clean
@@ -1,8 +1,10 @@
 #!/bin/sh
+#
 # Cleanup utility for z/OS Open Tools - https://github.com/ZOSOpenTools
+#
 
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -10,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -21,25 +23,25 @@ checkWritable
 printHelp()
 {
   cat << HELPDOC
-zopen clean is a utility for z/OS Open Tools to clean uneeded resources
-from the system to save space and prevent clutter
+${ME} is a utility for z/OS Open Tools to remove uneeded resources
+from the system to save space and prevent clutter.
 
-Usage: zopen clean [OPTION] [PACKAGE]
+Usage: ${ME} [OPTION] [PACKAGE]
 
 Options:
-  -m, --metadata    cleans and refreshes the metadata for zopen
+  --all             apply cleanup command to all applicable packages.
   -c, --cache  [PACKAGE ...]
-                    cleans the downloaded package cache; packages will be 
-                    re-downloaded if needed
-  -d, --dangling    removes dangling symlinks from the zopen file system in case 
-                    of issues during package maintenance
-  -u, --unused [PACKAGE ...]     
-                    remove versions of PACKAGEs that are available as 
-                    alternatives, leaving only the currently active version
-      --all         apply cleanup command to all applicable packages
-  -v, --verbose     run in verbose mode
-  -h,-?, --help     display this help and exit
-  --version         print version
+                    cleans the downloaded package cache; packages will be
+                    re-downloaded if needed.
+  -d, --dangling    removes dangling symlinks from the zopen file system in
+                    case of issues during package maintenance.
+  -h, --help, -?    display this help and exit.
+  -m, --metadata    cleans and refreshes the metadata for zopen.
+  -u, --unused [PACKAGE ...]
+                    remove versions of PACKAGEs that are available as
+                    alternatives, leaving only the currently active version.
+  -v, --verbose     run in verbose mode.
+  --version         print version.
 
 Examples:
   zopen clean -c    clear the package download cache
@@ -47,7 +49,7 @@ Examples:
   zopen clean -u [PACKAGE]
                     remove unused versions for PACKAGE
 
-Report bugs at https://github.com/ZOSOpenTools/meta/issues .
+Report bugs at https://github.com/ZOSOpenTools/meta/issues.
 
 HELPDOC
 }
@@ -55,11 +57,11 @@ HELPDOC
 cleanUnused()
 {
   for needle in $1; do
-    [ -z "${needle}" ] && return 
+    [ -z "${needle}" ] && return
     [ ! -e "${ZOPEN_PKGINSTALL}/${needle}" ] && printInfo "No versions of '${needle}' found" && continue
-    
+
     current=$(getCurrentVersionDir "${needle}")
-  
+
     if [ -n "${current}" ]; then
       current=$(basename "${current}")
     else
@@ -78,7 +80,7 @@ cleanUnused()
         printInfo "-- ${repo} <- Removed"
         syslog "${ZOPEN_LOG_PATH}/audit.log" "${LOG_A}" "${CAT_FILE},${CAT_PACKAGE},${CAT_REMOVE}" "CLEAN" "cleanUnused" "Removed unused package at ${repo#"${ZOPEN_PKGINSTALL}"/} "
       fi
-    done  
+    done
   done
 }
 
diff --git a/bin/zopen-compute-builddeps b/bin/zopen-compute-builddeps
--- a/bin/zopen-compute-builddeps
+++ b/bin/zopen-compute-builddeps
@@ -1,10 +1,10 @@
 #!/bin/env bash
-
 #
 # Print out build dependencies (transitive closure) for a given tool
 #
+
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -12,24 +12,33 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
 }
 setupMyself
 
+#
+# Display help text.
+#
 syntax()
 {
-  echo "$ME - print out build dependencies (transitive closure) for a given tool."
-  echo "  Note this tool will clone several repositories into a temporary directory for this computation."
-  echo "Usage: $ME [OPTION] [tool]"
-  echo "Options:"
-  echo "  --help     display this help and exit"
-  echo "  --version  print version"
-  echo "Examples:"
-  echo "  print out the tools required to build git"
-  echo "    $ME git"
+  cat << HELPDOC
+$ME - print out build dependencies (transitive closure) for a given tool.
+  NOTE: This tool will clone several repositories into a temporary directory
+  for this computation.
+
+Usage: $ME [OPTION] [tool]
+
+Options:
+  --help        display this help and exit.
+  --version     print version.
+
+Examples:
+  Print out the tools required to build git.
+    $ME git
+HELPDOC
   exit 0
 }
 
@@ -38,7 +47,7 @@ secondary_type="DEV"
 verbose=true
 
 if [ $# -eq 0 ]; then
-  echo "Need to specify a package name" >&2
+  echo "Need to specify a package name." >&2
   syntax
 fi
 
@@ -59,7 +68,7 @@ rootpkg="$1"
 tmpdir="/tmp/blddep_$$"
 
 if ! mkdir "${tmpdir}"; then
-  echo "Unable to create temporary directory for computing transitive closure" >&2
+  echo "Unable to create temporary directory for computing transitive closure." >&2
   syntax
 fi
 
diff --git a/bin/zopen-generate b/bin/zopen-generate
--- a/bin/zopen-generate
+++ b/bin/zopen-generate
@@ -1,10 +1,12 @@
 #!/bin/sh
+#
 # Initialize zopen
 ZOPEN_DONT_PROCESS_CONFIG=1
 # Generates a zopen compatible project
 #
+
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -12,7 +14,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -31,12 +33,11 @@ buildLicenseLookup()
 
 printSyntax()
 {
-  args=$*
   echo "zopen-generate will generate a zopen compatible project" >&2
   echo "Syntax: zopen-generate" >&2
 }
 
-if [[ $# -eq 1 ]]; then
+if [ $# -eq 1 ]; then
   if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
diff --git a/bin/zopen-help2man b/bin/zopen-help2man
--- a/bin/zopen-help2man
+++ b/bin/zopen-help2man
@@ -1,6 +1,12 @@
 #!/bin/sh
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# Routine to generate man pages from the --help and --version for the various tools.
+#
+# We may choose to use --extendedhelp if the --help output is too long for folks.
+#
+
+#
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -8,32 +14,29 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
 }
 setupMyself
 
-#
-# Routine to generate man pages from the --help and --version for the various tools
-#
-# We may choose to use --extendedhelp if the --help output is too long for folks
-#
 
 printSyntax()
 {
-  echo "${ME} - generate man pages from help and version information for zopen and zopen-* tools"
-  echo "Usage: ${ME} [OPTION] DIRECTORY"
-  echo "  DIRECTORY  the existing directory to write the man pages"
-  echo "Options:"
-  echo "  --help     display this help and exit"
-  echo "  --version  print version"
-  echo "Example:"
-  echo "  ${ME} /tmp/man1    write the man pages to the /tmp/man1 directory"
+  cat << HELPDOC
+${ME} - generate man pages from help and version information for zopen and zopen-* tools.
+Usage: ${ME} [OPTION] DIRECTORY
+  DIRECTORY  the existing directory to write the man pages.
+Options:
+  --help         display this help and exit
+  --version      print version
+Example:"
+  ${ME} /tmp/man1    write the man pages to the /tmp/man1 directory.
+HELPDOC
 }
 
-if [[ $# -eq 1 ]]; then
+if [ $# -eq 1 ]; then
   if [ "x$1" = "x--help" ]; then
     printSyntax
     exit 0
diff --git a/bin/zopen-init b/bin/zopen-init
--- a/bin/zopen-init
+++ b/bin/zopen-init
@@ -1,5 +1,6 @@
 #!/bin/sh
-# Initialize zopen
+# Initialize zopen environment - https://github.com/ZOSOpenTools
+#
 ME=$(basename "$0")
 
 if [ -z "${utildir}" ]; then
@@ -8,7 +9,7 @@ fi
 
 ZOPEN_DONT_PROCESS_CONFIG=1
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -16,7 +17,7 @@ setupMyself()
   MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -26,31 +27,26 @@ checkWritable
 
 printHelp(){
 cat << HELPDOC
-zopen init is a utility for z/OS Open Tools to generate a zopen 
+zopen init is a utility for z/OS Open Tools to generate a zopen
 environment, bootstrapping initial tools and creating a configuration
 file
 
 Usage: zopen init [OPTION] [PARAMETERS]...
 
 Options:
-  -y, --yes         
-          automatically answer 'yes' to prompts
-
   --append-to-profile
-          appends sourcing of zopen-config to current 
+          appends sourcing of zopen-config to current
           user's .profile
 
-  --releaseline-dev
-          globally configure the release line for package
-          installs to enable Development (DEV) packages; the
-          default is for a system to use STABLE packages
+  --[no]enable-stats
+          Toggle enabling collection of usage statistics
 
   -f, --fs-layout <LAYOUT>
-          The filesystem structure to use for installed 
-          packages on disk; packages will be installed to 
-          this location under <zopen rootfs>. 
+          The filesystem structure to use for installed
+          packages on disk; packages will be installed to
+          this location under <zopen rootfs>.
 
-          <LAYOUT> should be one of:                                         
+          <LAYOUT> should be one of:
 
             usrlclz: /usr/local/zopen (default),
             zopen: /usr/zopen,
@@ -59,28 +55,33 @@ Options:
             fhs: File Hierarchical Standard (/opt),
             usrlcl: usr/local
 
-  --re-init      
-          Re-initializes a previous zopen environment or 
-          create a new environment using current tooling.
-          Re-initializing over a previous installation will 
-          re-use existing package structures and 
-          configuration and regenerate configuration files.                    
-          select the active version for PACKAGE from a list
-
-  --refresh         
-          Refreshes the zopen-config file 
-
-  --[no]enable-stats
-          Toggle enabling collection of usage statistics
-
--v, --verbose     
-          run in verbose mode
-
--h, -?, --help    
+  -h, -?, --help
           display this help and exit
 
+  --re-init
+          Re-initializes a previous zopen environment or
+          create a new environment using current tooling.
+          Re-initializing over a previous installation will
+          re-use existing package structures and
+          configuration and regenerate configuration files.
+          select the active version for PACKAGE from a list
+
+  --refresh
+          Refreshes the zopen-config file
+
+  --releaseline-dev
+          globally configure the release line for package
+          installs to enable Development (DEV) packages; the
+          default is for a system to use STABLE packages
+
+  -v, --verbose
+          run in verbose mode
+
+  -y, --yes
+          automatically answer 'yes' to prompts
+
 Examples:
-  zopen init        
+  zopen init
           interactively bootstrap a zopen environment
 
   zopen init --releaseline-dev
@@ -88,14 +89,14 @@ Examples:
           will use Development Releaseline packages
 
   zopen --yes --append-to-profile --fs-layout fhs /zopen
-          non-interactively create a zopen environment at 
+          non-interactively create a zopen environment at
           location '/zopen' on disk, with packages installed
           to '/zopen/opt'. The user's .profile will be
           updated to source the configuration file at
-          '/zopen/etc/zopen-config' when new terminal 
+          '/zopen/etc/zopen-config' when new terminal
           sessions start
 
-Report bugs at https://github.com/ZOSOpenTools/meta/issues 
+Report bugs at https://github.com/ZOSOpenTools/meta/issues
 
 HELPDOC
 }
@@ -159,7 +160,7 @@ while [ $# -gt 0 ]; do
       zopen-version $ME
       exit 0
       ;;
-    "--debug") 
+    "--debug")
       debug=true
       ;;
     "--yes" | "-y")
@@ -329,8 +330,8 @@ generateFileSystem()
   fi
   printVerbose "Checking for existence of specified root: '${rootfs}'"
   [ -e "${rootfs}" ] || mkdir -p "${rootfs}" || printError "Unable to create zopen root filesystem at '${rootfs}'"
-  [ -d "${rootfs}" ] || printError "Specified location '${rootfs}' is not a directory. Unable to access root file system at '${rootfs}'; check permissions"  
-  [ -w "${rootfs}" ] || printError "Unable to write to root file system at '${rootfs}'; check permissions"  
+  [ -d "${rootfs}" ] || printError "Specified location '${rootfs}' is not a directory. Unable to access root file system at '${rootfs}'; check permissions"
+  [ -w "${rootfs}" ] || printError "Unable to write to root file system at '${rootfs}'; check permissions"
 
   printVerbose "- Populating standard file system"
   [ -e "${rootfs}/bin" ] || mkdir -p "${rootfs}/bin"
@@ -367,7 +368,7 @@ generateFileSystem()
 
 generateZopenConfig()
 {
-  printHeader "Generating zopen-config" 
+  printHeader "Generating zopen-config"
   writeConfigFile "${configFile}" "${rootfs}" "${zopen_pkginstall}" "${ZOPEN_CA_DIR}/${certFileName}"
   printInfo "- Created config in ${configFile}"
   if ${appendToProfile}; then
@@ -393,7 +394,7 @@ generateJsonConfiguration()
   if [ -z "$releaseLine" ]; then
     if ${releaselineDev}; then
       releaseLine="DEV"
-      printInfo "- Configured zopen to use development (DEV) releaseline packages where available" 
+      printInfo "- Configured zopen to use development (DEV) releaseline packages where available"
     else
       releaseLine="STABLE"
       printInfo "- Configured zopen to use stable releaseline packages"
diff --git a/bin/zopen-install b/bin/zopen-install
--- a/bin/zopen-install
+++ b/bin/zopen-install
@@ -1,7 +1,10 @@
 #!/bin/sh
+#
 # Install utility for z/OS Open Tools - https://github.com/ZOSOpenTools
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+
+#
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 # set -x
 setupMyself()
@@ -10,7 +13,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -23,27 +26,31 @@ printSyntax()
   args=$*
 cat << HELPDOC
 ${ME} is a utility to download/install a z/OS Open Tools package.
+
 Usage: ${ME} [OPION] [PACKAGE]
   [PACKAGE] is a package to install. Multiple packages can be specified.
+
 Options:
+  --all                    download/install all z/OS Open Tools packages.
+  --cache-only             do not install dependencies.
+  --download-only          download package to current directory.
   --help                   print this help.
-  --version                print version.
-  -u, --update, --upgrade  updates installed z/OS Open Tools packages.
   --install-or-upgrade     installs the package if not installed,
                            or upgrades the package if installed.
-  -r, --reinstall          reinstall already installed z/OS Open Tools packages.
-  --nosymlink              do not integrate into filesystem through symlink redirection.
-  --release-line [stable, dev] the release line to build off of.
-  --no-deps                do not install dependencies.
-  --cache-only             do not install dependencies.
-  --no-set-active          do not change the pinned version.
-  --skip-upgrade           do not upgrade.
-  -y, --yes                automatically answer yes to prompts.
-  --select                 select a version to install.
-  -v, --verbose            print verbose messages.
-  --download-only          download package to current directory.
   --local-install          download and unpackage to current directory.
-  --all                    download/install all z/OS Open Tools packages.
+  --no-deps                do not install dependencies.
+  --no-set-active          do not change the pinned version.
+  --nosymlink              do not integrate into filesystem through
+                           symlink redirection.
+  -r, --reinstall          reinstall already installed z/OS Open Tools packages.
+  --release-line [stable, dev] the release line to build off of.
+  --select                 select a version to install.
+  --skip-upgrade           do not upgrade.
+  -u, --update, --upgrade  updates installed z/OS Open Tools packages.
+  -v, --verbose            print verbose messages.
+  --version                print version.
+  -y, --yes                automatically answer yes to prompts.
+
 HELPDOC
 }
 
diff --git a/bin/zopen-remove b/bin/zopen-remove
--- a/bin/zopen-remove
+++ b/bin/zopen-remove
@@ -1,7 +1,10 @@
 #!/bin/sh
+#
 # Removal utility for z/OS Open Tools - https://github.com/ZOSOpenTools
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+
+#
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -9,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -20,24 +23,25 @@ checkWritable
 printHelp()
 {
   cat << HELPDOC
-zopen remove is a utility for z/OS Open Tools to remove an installed package or
+${ME} is a utility for z/OS Open Tools to remove an installed package or
 packages.
 
-Usage: zopen remove [OPTION] [PACKAGE] ...
+Usage: ${ME} [OPTION] [PACKAGE] ...
 
 Options:
+  -h, --help, -?    display this help and exit.
+  -p, --purge       remove package, the versioned directory, and any
+                    cached files.
+  -v, --verbose     run in verbose mode.
+  --version         print version.
   -y, --yes         automatically answer yes to prompts.
-  -p, --purge       remove package, the versioned directory and any cached file
-  -v, --verbose     run in verbose mode
-  -h, -?, --help    display this help and exit
-  --version         print version
 
 Examples:
   zopen remove foo bar
                     interactively remove the foo and bar packages if installed
   zopen remove --yes foo bar
-                    remove the foo and bar packages if installed, without asking
-                    for confirmation
+                    remove the foo and bar packages if installed, without
+                    asking for confirmation
 
 Report bugs at https://github.com/ZOSOpenTools/meta/issues .
 
@@ -131,7 +135,7 @@ while [ $# -gt 0 ]; do
     # shellcheck disable=SC2034
     debug=true
     ;;
-  "-y" | "--yes") 
+  "-y" | "--yes")
     yesToPrompts=true
     ;;
   *)
diff --git a/bin/zopen-split-patch b/bin/zopen-split-patch
--- a/bin/zopen-split-patch
+++ b/bin/zopen-split-patch
@@ -1,6 +1,10 @@
 #!/bin/env bash
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# Split a patch file into multiple patches.
+#
+
+#
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -8,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -22,12 +26,16 @@ printSyntax()
   cat << HELPDOC
 ${ME} - split a patch file into one patch file for each patch.
   Patches are written to ${pd} in the current directory.
+
 Usage: ${ME} [OPTION] [PATCHFILE]
+
 Options:
   --help      display this help and exit.
   --version   print version.
+
 Example:
   ${ME} P1.patch    write P1.patch into multiple patches under ${pd}
+
 HELPDOC
 }
 
diff --git a/bin/zopen-update-cacert b/bin/zopen-update-cacert
--- a/bin/zopen-update-cacert
+++ b/bin/zopen-update-cacert
@@ -2,8 +2,9 @@
 #
 # Updates the cacert in zopen meta root directory
 #
+
 #
-# All zopen-* scripts MUST start with this code to maintain consistency
+# All zopen-* scripts MUST start with this code to maintain consistency.
 #
 setupMyself()
 {
@@ -11,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -40,19 +41,23 @@ printHelp()
 {
   args=$*
 cat << HELPDOC
-${ME}:
-  Update your cacert.pem file to the latest curl CA certificates extracted from Mozilla.
+${ME}: Update your cacert.pem file to the latest CA certificates extracted from Mozilla.
+
 Syntax:
   ${ME} [-fhv] [<directory>]
+
 Options:
   -f, --force           update cacert.pem file even if up to date.
   -h, --help            print this help.
+  -i, --insecure-fallback
+                        (UNSAFE) Skip certificate validation during download.
   -v, --verbose         print verbose messages.
   --version             print version.
 
 Parameters:
   <directory>: the directory where the cacert.pem will be updated.
     The default directory location is: ${default_dir}
+
 HELPDOC
 }
 
@@ -118,12 +123,12 @@ dir="${default_dir}"
 args=$*
 forceUpdate=false
 insecureFallback=false
-while [[ $# -gt 0 ]]; do
+while [ $# -gt 0 ]; do
   case "$1" in
-  "-f" | "-force" | "--force")
+  "-f" | "--force")
     forceUpdate=true
     ;;
-  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
+  "-h" | "--help" | "-?")
     printHelp "${args}"
     exit 0
     ;;
@@ -134,7 +139,7 @@ while [[ $# -gt 0 ]]; do
   "-i" | "--insecure-fallback")
     insecureFallback=true
     ;;
-  "-v" | "--v" | "-verbose" | "--verbose")
+  "-v" | "--verbose")
     verbose=true
     ;;
   *)
