Format zopen scripts

diff --git a/bin/zopen-alt b/bin/zopen-alt
--- a/bin/zopen-alt
+++ b/bin/zopen-alt
@@ -5,20 +5,21 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename $0)
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
-printHelp(){
-cat << HELPDOC
+printHelp()
+{
+  cat <<HELPDOC
 zopen alt is a utility for z/OS Open Tools to switch package versions 
 for currently installed packages.
 
@@ -47,7 +48,8 @@ Report bugs at https://github.com/ZOSOpenTools/meta/issues .
 HELPDOC
 }
 
-mergeNewVersion(){
+mergeNewVersion()
+{
   package="$1"
   newver="$2"
   [ -d "$ZOPEN_PKGINSTALL/$package/$newver" ] || printError "Version '$newver' was not available to set as current"
@@ -55,7 +57,7 @@ mergeNewVersion(){
     printVerbose "Removing main link"
     rm -rf "$ZOPEN_PKGINSTALL/$package/$package"
   fi
-  mergeIntoSystem "$package" "$ZOPEN_PKGINSTALL/$package/$newver" "$ZOPEN_ROOTFS" 
+  mergeIntoSystem "$package" "$ZOPEN_PKGINSTALL/$package/$newver" "$ZOPEN_ROOTFS"
   printVerbose "New version merged; checking for orphaned files from previous version"
   # This will remove any old symlinks or dirs that might have changed in an up/downgrade
   # as the merge process overwrites existing files to point to different version. If there was
@@ -64,8 +66,8 @@ mergeNewVersion(){
     unsymlinkFromSystem "$package" "$ZOPEN_ROOTFS" "${ZOPEN_PKGINSTALL}/$package/$deref/.links"
   else
     printVerbose "No previous version found (no .links) - no unlinking performed"
-  fi 
-  
+  fi
+
   misrc=$?
   printVerbose "The merge completed with: $misrc"
   printVerbose "Generating main link from $package to version: $newver"
@@ -80,7 +82,8 @@ mergeNewVersion(){
   syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_PACKAGE" "ALT" "setAlt" "Set '${package}' to version:$version;"
 }
 
-setAlt(){
+setAlt()
+{
   package="$1"
   newver="$2"
   if [ -e "$ZOPEN_PKGINSTALL/$package/" ]; then
@@ -100,34 +103,36 @@ setAlt(){
   mergeNewVersion "$package" "$newver"
 }
 
-selectAlt(){
+selectAlt()
+{
   i=$1
   package=$2
   printVerbose "Selecting alternative"
-    valid=false
-    while ! $valid; do
-      echo "Enter alternative version to use (1-$i): "
-      selection=$(getInput)
-      if [ ! -z "$(echo $selection | sed -e 's/[0-9]*//')" ]; then
-        echo "Invalid input, must be a number between 1 and $i"
-      elif [ "$selection" -ge 1 ] && [ "$selection" -le "$i" ]; then
-        valid=true
-      fi
-    done
-    if [ ! "$selection" -eq "$current" ]; then
-      newver="$(echo $found | awk -v selection="$selection" '
+  valid=false
+  while ! $valid; do
+    echo "Enter alternative version to use (1-$i): "
+    selection=$(getInput)
+    if [ ! -z "$(echo $selection | sed -e 's/[0-9]*//')" ]; then
+      echo "Invalid input, must be a number between 1 and $i"
+    elif [ "$selection" -ge 1 ] && [ "$selection" -le "$i" ]; then
+      valid=true
+    fi
+  done
+  if [ ! "$selection" -eq "$current" ]; then
+    newver="$(echo $found | awk -v selection="$selection" '
         BEGIN {count=0}
               {count = count + 1; if (count=selection) { print $(selection)} }
       ')"
-      printInfo "selecting alternative: $selection: $newver"
-      mergeNewVersion "$package" "$newver"
-    else
-      printInfo "Selection is already current version."
-      exit 0
-    fi
+    printInfo "selecting alternative: $selection: $newver"
+    mergeNewVersion "$package" "$newver"
+  else
+    printInfo "Selection is already current version."
+    exit 0
+  fi
 }
 
-listAlts(){
+listAlts()
+{
   select=$1
   package="$2"
 
@@ -150,12 +155,12 @@ listAlts(){
 
   i=0
   current=0
-# just the below would be simpler, but creates a subshell so can't get the number of entries outside!  
-#  echo "$found" | xargs | tr ' ' '\n' | while read repo; do
+  # just the below would be simpler, but creates a subshell so can't get the number of entries outside!
+  #  echo "$found" | xargs | tr ' ' '\n' | while read repo; do
   TMP_FIFO_PIPE="$HOME/altselect.pipe"
   [ ! -p "$TMP_FIFO_PIPE" ] || rm -f "$TMP_FIFO_PIPE"
   mkfifo $TMP_FIFO_PIPE
-  echo "$found" | xargs | tr ' ' '\n' >> "$TMP_FIFO_PIPE" &
+  echo "$found" | xargs | tr ' ' '\n' >>"$TMP_FIFO_PIPE" &
   while read repo; do
     printVerbose "Parsing repo: '$repo' as '${repo#$ZOPEN_PKGINSTALL/}'"
     i=$(expr $i + 1)
@@ -165,7 +170,7 @@ listAlts(){
     else
       printInfo "$i: ${repo#"$ZOPEN_PKGINSTALL"/}"
     fi
-  done < "$TMP_FIFO_PIPE"
+  done <"$TMP_FIFO_PIPE"
   [ ! -p $TMP_FIFO_PIPE ] || rm -rf "$TMP_FIFO_PIPE"
 
   if $select; then
@@ -178,12 +183,11 @@ listAlts(){
   exit 0
 }
 
-
 # Main code start here
 args=$*
 verbose=false
 debug=false
-sett=false  #sett to distinguish from "set" command
+sett=false #sett to distinguish from "set" command
 select=false
 if [ $# -eq 0 ]; then
   printError "Missing program argument"
@@ -191,42 +195,42 @@ fi
 while [ $# -gt 0 ]; do
   printVerbose "Parsing option: $1"
   case "$1" in
-    "-s" | "--set")
-      shift
-      [ $# -lt 2 ] && printError "Missing argument(s) for set option. Check program arguments"
-      sett=true
-      select=false
-      package="$1"
-      newver="$2"
-      shift
+  "-s" | "--set")
+    shift
+    [ $# -lt 2 ] && printError "Missing argument(s) for set option. Check program arguments"
+    sett=true
+    select=false
+    package="$1"
+    newver="$2"
+    shift
     ;;
-    "--select")
-      select=true
-      sett=false
-      shift
-      [ $# -lt 1 ] && printError "Missing argument for select option."
-      package="$1"
-      ;;
-    "-h" | "--help" | "-?")
-      printHelp "${args}"
-      exit 0
-      ;;
-    "--version")
-      zopen --version $ME
-      exit 0
-      ;;
-    "-v" | "--verbose")
-      verbose=true
-      ;;
-    "--debug")
-      verbose=true
-      debug=true
-      ;;
-    *)
-      package="$1"; # Multiple packages will result in the last package only
-      ;;
+  "--select")
+    select=true
+    sett=false
+    shift
+    [ $# -lt 1 ] && printError "Missing argument for select option."
+    package="$1"
+    ;;
+  "-h" | "--help" | "-?")
+    printHelp "${args}"
+    exit 0
+    ;;
+  "--version")
+    zopen --version $ME
+    exit 0
+    ;;
+  "-v" | "--verbose")
+    verbose=true
+    ;;
+  "--debug")
+    verbose=true
+    debug=true
+    ;;
+  *)
+    package="$1" # Multiple packages will result in the last package only
+    ;;
   esac
-  shift;
+  shift
 done
 
 if $sett; then
diff --git a/bin/zopen-clean b/bin/zopen-clean
--- a/bin/zopen-clean
+++ b/bin/zopen-clean
@@ -6,20 +6,21 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename $0)
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
-printHelp(){
-cat << HELPDOC
+printHelp()
+{
+  cat <<HELPDOC
 zopen clean is a utility for z/OS Open Tools to clean uneeded resources
 from the system to save space and prevent clutter
 
@@ -47,10 +48,10 @@ Report bugs at https://github.com/ZOSOpenTools/meta/issues .
 HELPDOC
 }
 
-
-cleanUnused(){
+cleanUnused()
+{
   needle=$1
-  found=$(zosfind "$ZOPEN_PKGINSTALL" -name "*/${needle}-*" -prune -type d )
+  found=$(zosfind "$ZOPEN_PKGINSTALL" -name "*/${needle}-*" -prune -type d)
   if [ -z "$found" ]; then
     printInfo "No versions of package '${needle}' found for removal"
     return
@@ -65,12 +66,12 @@ cleanUnused(){
 
   i=0
   current=0
-# the below would be simpler, but creates a subshell so can't get the number of entries outside!  
-#  echo "$found" | xargs | tr ' ' '\n' | while read repo; do
+  # the below would be simpler, but creates a subshell so can't get the number of entries outside!
+  #  echo "$found" | xargs | tr ' ' '\n' | while read repo; do
   TMP_FIFO_PIPE="$HOME/altselect.pipe"
   [ ! -p "$TMP_FIFO_PIPE" ] || rm -f "$TMP_FIFO_PIPE"
   mkfifo "$TMP_FIFO_PIPE"
-  echo "$found" | xargs | tr ' ' '\n'>> "$TMP_FIFO_PIPE" &
+  echo "$found" | xargs | tr ' ' '\n' >>"$TMP_FIFO_PIPE" &
   while read repo; do
     printVerbose "Parsing repo: '$repo' as '${repo#$ZOPEN_PKGINSTALL/}'"
     if [ "${repo}" = "${repo#$ZOPEN_PKGINSTALL/}" ]; then
@@ -89,19 +90,20 @@ cleanUnused(){
       current=$i
       printInfo "${NC}${GREEN}$i: ${repo#$ZOPEN_PKGINSTALL/}  <-  current${NC}"
     else
-      rm -rf "$repo" >/dev/null 2>&1 
+      rm -rf "$repo" >/dev/null 2>&1
       printInfo "$i: ${repo#$ZOPEN_PKGINSTALL/} <- Removed"
       syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_FILE,$CAT_PACKAGE,$CAT_REMOVE" "CLEAN" "cleanUnused" "Removed unused package at ${repo#$ZOPEN_PKGINSTALL/} "
     fi
-  done < "$TMP_FIFO_PIPE"
+  done <"$TMP_FIFO_PIPE"
   [ ! -p "$TMP_FIFO_PIPE" ] || rm -f "$TMP_FIFO_PIPE"
-  printInfo "- Removal of unused package versions complete" 
+  printInfo "- Removal of unused package versions complete"
 }
 
-cleanDangling(){
+cleanDangling()
+{
   printVerbose "Removing dangling symlinks from the file structure"
   # As packages can install to any subfolder of the zopen filesystem, need to traverse
-    # along every path under that filesystem
+  # along every path under that filesystem
   if [ "$ZOPEN_ROOTFS" = "/." ]; then
     printWarning "With zopen's root configured as '/', traversal to find dangling symlinks"
     printWarning "will occur on ALL mounted file systems, ALL sub-directories and will"
@@ -112,7 +114,7 @@ cleanDangling(){
     printWarning "within the zopen file structure so all locations need to be considered"
     printWarning "and analysed."
     printWarning "Are you absolutely sure you want to run this option (y/N)?"
-    read absolutely < /dev/tty
+    read absolutely </dev/tty
     if [ -n "$absolutely" ] && [ "y" = "${absolutely}" ]; then
       printInfo "- Checking for any dangling symlinks across system"
     else
@@ -129,11 +131,12 @@ cleanDangling(){
     rm -f $sl
     flecnt=$(expr $flecnt + 1)
   done
-  $killph 2>/dev/null  # if the timer is not running, the kill will fail
+  $killph 2>/dev/null # if the timer is not running, the kill will fail
   syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_FILE" "CLEAN" "cleanDangling" "zopen system scanned for dangling symlinks; $flecnt link(s) removed"
 }
 
-cleanCache(){
+cleanCache()
+{
   printVerbose "Cleaning $ZOPEN_ROOTFS/var/cache/zopen"
   rm -rf "$ZOPEN_ROOTFS/var/cache/zopen/*"
   syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_FILE" "CLEAN" "cleanCache" "Main cache in $ZOPEN_ROOTFS/var/cache/zopen cleaned"
@@ -155,53 +158,52 @@ fi
 while [ $# -gt 0 ]; do
   printVerbose "Parsing option: $1"
   case "$1" in
-      "-u" | "--unused")
-      shift
-      [ $# -lt 1 ] && printError "Missing parameter for 'clean unused' option"
-      unused=true
-      dangling=false
-      cache=false
-      package="$1"
-      ;;
-      "-d" | "--dangling")
-      unused=false
-      dangling=true
-      cache=false
-      ;;
-      "-c" | "--cache")
-      unused=false
-      dangling=false
-      cache=true
-      ;;
-    "-h" | "--help" | "-?" )
-      printHelp "${args}"
-      exit 0
-      ;;
-    "--version" )
-      zopen --version $ME
-      exit 0
-      ;;
-    "-v" | "--verbose")
-      verbose=true
-      ;;
-    "--debug")
-      verbose=true
-      debug=true
-      ;;
-    *)
-      package="$1"; # Use the last unrecognised parameter as the package
-      ;;
+  "-u" | "--unused")
+    shift
+    [ $# -lt 1 ] && printError "Missing parameter for 'clean unused' option"
+    unused=true
+    dangling=false
+    cache=false
+    package="$1"
+    ;;
+  "-d" | "--dangling")
+    unused=false
+    dangling=true
+    cache=false
+    ;;
+  "-c" | "--cache")
+    unused=false
+    dangling=false
+    cache=true
+    ;;
+  "-h" | "--help" | "-?")
+    printHelp "${args}"
+    exit 0
+    ;;
+  "--version")
+    zopen --version $ME
+    exit 0
+    ;;
+  "-v" | "--verbose")
+    verbose=true
+    ;;
+  "--debug")
+    verbose=true
+    debug=true
+    ;;
+  *)
+    package="$1" # Use the last unrecognised parameter as the package
+    ;;
   esac
-  shift;
+  shift
 done
 
-if $unused; then 
+if $unused; then
   cleanUnused "$package"
 fi
-if $dangling; then 
+if $dangling; then
   cleanDangling
 fi
 if $cache; then
   cleanCache
 fi
-
diff --git a/bin/zopen-migrate-groovy b/bin/zopen-migrate-groovy
--- a/bin/zopen-migrate-groovy
+++ b/bin/zopen-migrate-groovy
@@ -10,14 +10,14 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename $0)
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -79,4 +79,3 @@ ${description}
 
 echo "${dev}" >cicd-dev.groovy
 echo "${stable}" >cicd-stable.groovy
-
diff --git a/bin/zopen-query b/bin/zopen-query
--- a/bin/zopen-query
+++ b/bin/zopen-query
@@ -5,26 +5,26 @@
 #
 setupMyself()
 {
-        ME=$(basename $0)
-        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
-        INCDIR="${MYDIR}/../include"
-        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-                echo "Internal Error. Unable to find common.sh file to source" >&2
-                exit 8
-        fi
-        . "${INCDIR}/common.sh"
+  ME=$(basename $0)
+  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
+  INCDIR="${MYDIR}/../include"
+  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+    echo "Internal Error. Unable to find common.sh file to source" >&2
+    exit 8
+  fi
+  . "${INCDIR}/common.sh"
 }
 setupMyself
 
-printSyntax() 
+printSyntax()
 {
   args=$*
   echo "zopen query is a utility for z/OS Open Tools to query packages and repos." >&2
   echo "Syntax: zopen-query [<option>]* [<package]*" >&2
   echo "  where <option> may be one or more of:" >&2
-  echo "  --help: print this help"  >&2
-  echo "  --version: print version"  >&2
-  echo "  --list: list all available z/OS Open Tools."  >&2
+  echo "  --help: print this help" >&2
+  echo "  --version: print version" >&2
+  echo "  --list: list all available z/OS Open Tools." >&2
   echo "  --remote-search: regex match package against available z/OS Open Tools" >&2
   echo "  -i : --installed: list install z/OS Open Tools." >&2
   echo " --upgradeable: list packages where an upgrade is available." >&2
@@ -33,11 +33,12 @@ printSyntax()
   echo "  -d | --details: include full details for listings." >&2
   echo "  --no-header: suppress the header for the output." >&2
   echo "  --no-version:  suppress version information, return package names." >&2
-  echo "  --filter <color>: apply filter based on quality (green - all tests passing, blue - most tests passing, yellow - some tests passing, red - no tests passing, or skipped (no filter by default))"  >&2
+  echo "  --filter <color>: apply filter based on quality (green - all tests passing, blue - most tests passing, yellow - some tests passing, red - no tests passing, or skipped (no filter by default))" >&2
   echo " and <package> is an optional list of one or more packages." >&2
 }
 
-colorizepct(){
+colorizepct()
+{
   percentage=$1
   if [ -z "$percentage" ]; then
     colored="${RED}"
@@ -64,7 +65,7 @@ printDetailListEntries()
   if [ "$details" -eq 0 ]; then
     scrcols=$(getScreenCols)
     numcols=4
-    colwidth=$((scrcols / numcols -1 ))
+    colwidth=$((scrcols / numcols - 1))
     printVerbose "Screen width: $scrcols; colwidth:$colwidth"
     if [ ! -z "$1" ] && ! $noheader; then
       printf "${NC}${UNDERLINE}%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s${NC}\n" "Package" "Installed" "Available" "Latest Tag"
@@ -79,7 +80,7 @@ printDetailListEntries()
           listport=true
         fi
       fi
-    
+
       if $listport; then
         latest=$(jq -e -r '.release_data."'$repo'"[0]' "$JSON_CACHE")
         if [ $? -ne 0 ]; then
@@ -99,21 +100,21 @@ printDetailListEntries()
         fi
         if [ "$onlyUpgradesAvailable" -gt 0 ]; then
           if [ "$originalVersion" = "Not installed" -o "$originalVersion" = "$latestVersion" ]; then
-            continue;
-          fi 
+            continue
+          fi
         fi
         if ! $noversions; then
           printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s\n" "$repo" "$originalVersion" "$dotversion" "$latestVersion"
         else
           printf "%s\n" "$repo"
         fi
-      fi 
+      fi
     done
   else
     printVerbose "Checking repoArray: $repoArray"
     scrcols=$(getScreenCols)
     numcols=6
-    colwidth=$((scrcols / numcols -1 ))
+    colwidth=$((scrcols / numcols - 1))
     printVerbose "Screen width: $scrcols; colwidth:$colwidth"
     if ! $noheader; then
       printf "${NC}${UNDERLINE}%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s${NC}\n" "Package" "Installed" "Latest Tag" "Download Size" "Expanded Size" "Quality"
@@ -128,7 +129,7 @@ printDetailListEntries()
           listport=true
         fi
       fi
-    
+
       if $listport; then
         pkghome="$ZOPEN_PKGINSTALL/${repo}/${repo}"
         if [ -e "${pkghome}/.releaseinfo" ]; then
@@ -138,47 +139,50 @@ printDetailListEntries()
         fi
         latest=$(jq -e -r '.release_data."'$repo'"[0]' "$JSON_CACHE")
         case $? in
-          1) printVerbose "No latest release for port";
-               printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s ${NC}${RED}%-${colwidth}s${NC}\n" "$repo" "$originalTag" "Unknown" "Unknown" "Unknown" "Unknown" 
-               ;;
-          0) printVerbose "Latest release request successful";  
-               latestTag="$(/bin/printf "%s" "$latest" | jq -e -r '.tag_name')"
-               passed="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].passed_tests')"
-               total="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].total_tests')"
-               expandedsize="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].expanded_size')"
-               downloadsize="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].size')"
-               if [ "$onlyUpgradesAvailable" -gt 0 ]; then
-                 if [ "$originalTag" = "Not installed" -o "$originalTag" = "$latestTag" ]; then
-                   continue;
-                 fi 
-               fi
-               if [ $total -gt 0 ]; then
-                 percentage=$(echo "scale=0; 100 * ($passed) / $total" | bc)
-               fi
-               printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s " "$repo" "$originalTag" "$latestTag" 
-               printf " %-${colwidth}s"  "$downloadsize"
-               printf " %-${colwidth}s"  "$expandedsize"
+        1)
+          printVerbose "No latest release for port"
+          printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s ${NC}${RED}%-${colwidth}s${NC}\n" "$repo" "$originalTag" "Unknown" "Unknown" "Unknown" "Unknown"
+          ;;
+        0)
+          printVerbose "Latest release request successful"
+          latestTag="$(/bin/printf "%s" "$latest" | jq -e -r '.tag_name')"
+          passed="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].passed_tests')"
+          total="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].total_tests')"
+          expandedsize="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].expanded_size')"
+          downloadsize="$(/bin/printf "%s" "$latest" | jq -e -r '.assets[0].size')"
+          if [ "$onlyUpgradesAvailable" -gt 0 ]; then
+            if [ "$originalTag" = "Not installed" -o "$originalTag" = "$latestTag" ]; then
+              continue
+            fi
+          fi
+          if [ $total -gt 0 ]; then
+            percentage=$(echo "scale=0; 100 * ($passed) / $total" | bc)
+          fi
+          printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s " "$repo" "$originalTag" "$latestTag"
+          printf " %-${colwidth}s" "$downloadsize"
+          printf " %-${colwidth}s" "$expandedsize"
 
-               if [ -z "$percentage" ]; then
-                 printf "${NC}${RED}%-${colwidth}s${NC}" "No tests"
-               else
-                 printf "${NC}%s%-${colwidth}s${NC}" "$(colorizepct "$percentage" )" "$percentage%"
-               fi
-               printf "\n"
-               ;;
-          *) printError "Error while trying to retrieve latest repo release";;
+          if [ -z "$percentage" ]; then
+            printf "${NC}${RED}%-${colwidth}s${NC}" "No tests"
+          else
+            printf "${NC}%s%-${colwidth}s${NC}" "$(colorizepct "$percentage")" "$percentage%"
+          fi
+          printf "\n"
+          ;;
+        *) printError "Error while trying to retrieve latest repo release" ;;
         esac
 
       fi
-      continue;   
+      continue
     done
   fi
   exit 0
 }
-printInstalledEntries(){
+printInstalledEntries()
+{
   scrcols=$(getScreenCols)
   [ $details -eq 0 ] && numcols=4 || numcols=6
-  colwidth=$(($scrcols / $numcols -1 ))
+  colwidth=$(($scrcols / $numcols - 1))
   printVerbose "Screen width: $scrcols; colwidth:$colwidth"
   if [ ! -z "$1" ] && ! $noheader; then
     if [ $details -eq 0 ]; then
@@ -221,18 +225,18 @@ printInstalledEntries(){
     if [ -z "$releaseline" ]; then
       releaseline="n/a"
     fi
-  
+
     printVerbose "Original tag: $originalTag for repo: $repo"
     if [ -z "$1" ]; then
       printInfo "$originalTag"
     else
-      fileversion="$( cd "$ZOPEN_PKGINSTALL/${repo}/${repo}" >/dev/null 2>&1 && pwd -P | xargs basename)"
+      fileversion="$(cd "$ZOPEN_PKGINSTALL/${repo}/${repo}" >/dev/null 2>&1 && pwd -P | xargs basename)"
       printf "%-${colwidth}s %-${colwidth}s %-${colwidth}s %-${colwidth}s" "$repo" "$dotversion" "$fileversion" "$releaseline"
       if [ $details -eq 1 ]; then
         # Extra headers: disk size and quality
-        disksizestr=$(du "$ZOPEN_PKGINSTALL/${repo}" |tail -n 1 )
+        disksizestr=$(du "$ZOPEN_PKGINSTALL/${repo}" | tail -n 1)
         disksizestr=$(echo $disksizestr | sed 's#\([0-9]*\).*#\1#')
-        disksize=$(( $disksizestr * 512 ))
+        disksize=$(($disksizestr * 512))
         printf "%-${colwidth}d" $disksize
 
         if [ -e "${pkghome}/test.status" ]; then
@@ -240,34 +244,35 @@ printInstalledEntries(){
           percentage=$(echo "$teststatus" | sed 's/[^-]*-\([^%\.]*\).*/\1/')
           printf "${NC}$s%-${colwidth}s${NC}" "$(colorizepct "$percentage")" "$percentage"
         else
-           printf "${NC}${RED}%-${colwidth}s${NC}" "No tests"
+          printf "${NC}${RED}%-${colwidth}s${NC}" "No tests"
         fi
       fi
-      
+
       printf "\n"
     fi
   done
   exit 0
 }
 
-whatProvides(){
+whatProvides()
+{
   needle="$1"
   printVerbose "Finding matches outside of ZOPEN_PKGINSTALL ($ZOPEN_PKGINSTALL)"
   # Find any symlinks that match the needle and can then be dereferenced
-  found=$(zosfind "$ZOPEN_ROOTFS" -name "$ZOPEN_PKGINSTALL/\*" -prune -o -type l -print | grep "${needle}") 
+  found=$(zosfind "$ZOPEN_ROOTFS" -name "$ZOPEN_PKGINSTALL/\*" -prune -o -type l -print | grep "${needle}")
   printVerbose "Found list: '$found'"
   if [[ -z "$found" ]]; then
     printInfo "No package provides '${needle}'"
   else
-    matches=$(echo "$found"| wc -w | tr -d ' ' ) 
+    matches=$(echo "$found" | wc -w | tr -d ' ')
     printInfo "Found ${matches} match$([ $matches = 1 ] && echo "" || echo "es") for regex '${needle}' on the system"
     echo "$found" | xargs | tr ' ' '\n' | while read foundmatch; do
       printVerbose "Parsing '$foundmatch'"
       if [ ! -d "$foundmatch" ]; then
-      dereferenced=$(deref "$foundmatch")
-      fullpackage=$(echo "$dereferenced" | sed "s#$ZOPEN_PKGINSTALL/\([^/]*\).*#\1#")
-      
-      printInfo "Package '$fullpackage' provides: '$foundmatch'"
+        dereferenced=$(deref "$foundmatch")
+        fullpackage=$(echo "$dereferenced" | sed "s#$ZOPEN_PKGINSTALL/\([^/]*\).*#\1#")
+
+        printInfo "Package '$fullpackage' provides: '$foundmatch'"
       fi
     done
   fi
@@ -290,66 +295,66 @@ fi
 while [[ $# -gt 0 ]]; do
   printVerbose "Parsing option: $1"
   case "$1" in
-    "--list")
-      list=1;
-      localoption=false;
-      ;;
-    "-i" | "--installed")
-      localoption=true;
-      installed=1;
-      list=;
+  "--list")
+    list=1
+    localoption=false
     ;;
-    "-wp" | "--whatprovides")
-      localoption=true;
-      whatprovides=1;
-      shift;
-      [ ! -z $1 ] || printError "Missing file argument";
-      needle=$1;
+  "-i" | "--installed")
+    localoption=true
+    installed=1
+    list=
     ;;
-    "--remote-search")
-      localoption=false;
-      remotesearch=1;
-      shift;
-      [ ! -z $1 ] || printError "Missing package argument";
-      needle=$1;
+  "-wp" | "--whatprovides")
+    localoption=true
+    whatprovides=1
+    shift
+    [ ! -z $1 ] || printError "Missing file argument"
+    needle=$1
     ;;
-    "--no-header")
-      noheader=true;
+  "--remote-search")
+    localoption=false
+    remotesearch=1
+    shift
+    [ ! -z $1 ] || printError "Missing package argument"
+    needle=$1
     ;;
-    "--upgradeable")
-      upgradeable=true;
+  "--no-header")
+    noheader=true
     ;;
-    "--no-versions")
-      noversions=true;
-      noheader=true; # headers do not mean anything without versions!
+  "--upgradeable")
+    upgradeable=true
     ;;
-    "-f" | "--filter")
-      filter=$2;
-      shift
-      ;;
-    "-d"  | "--details")
-      details=1;
+  "--no-versions")
+    noversions=true
+    noheader=true # headers do not mean anything without versions!
     ;;
-    "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
-      printSyntax "${args}"
-      exit 0
-      ;;
-    "--version")
-      zopen --version $ME
-      exit 0
-      ;;
-    "-v" | "--v" | "-verbose" | "--verbose")
-      verbose=true
-      ;;
-    -*)
-      printError "Unknown option '$1'"
-      ;;
-     
-    *)
-      chosenRepos="$chosenRepos $1";
-      ;;
+  "-f" | "--filter")
+    filter=$2
+    shift
+    ;;
+  "-d" | "--details")
+    details=1
+    ;;
+  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
+    printSyntax "${args}"
+    exit 0
+    ;;
+  "--version")
+    zopen --version $ME
+    exit 0
+    ;;
+  "-v" | "--v" | "-verbose" | "--verbose")
+    verbose=true
+    ;;
+  -*)
+    printError "Unknown option '$1'"
+    ;;
+
+  *)
+    chosenRepos="$chosenRepos $1"
+    ;;
   esac
-  shift;
+  shift
 done
 
 checkIfConfigLoaded
@@ -361,8 +366,8 @@ export CURL_CA_BUNDLE="${ZOPEN_CA}"
 if [ ! -z "$filter" ]; then
   filter=$(echo "$filter" | awk '{print tolower($0)}')
   case "$filter" in
-      blue|green|yellow|red|skipped) ;;
-      *) printError "The filter must be one of blue|green|yellow|red"
+  blue | green | yellow | red | skipped) ;;
+  *) printError "The filter must be one of blue|green|yellow|red" ;;
   esac
 fi
 
@@ -370,7 +375,7 @@ if ! $localoption; then
   # Retrieve all repositories
   getReposFromGithub
   grfgRc=$?
-  [ 0 -ne $grfgRc ] && exit $grfgRc;
+  [ 0 -ne $grfgRc ] && exit $grfgRc
   repoArray="$repo_results"
 fi
 
