Add period to error message

diff --git a/bin/zopen-compute-builddeps b/bin/zopen-compute-builddeps
--- a/bin/zopen-compute-builddeps
+++ b/bin/zopen-compute-builddeps
@@ -15,7 +15,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
@@ -29,8 +29,8 @@ syntax()
 {
   cat << HELPDOC
 $ME - print out build dependencies (transitive closure) for a given tool.
-  NOTE: This tool will clone several repositories into a
-  temporary directory for this computation.
+  NOTE: This tool will clone several repositories into a temporary directory
+  for this computation.
 
 Usage: $ME [OPTION] [tool]
 
diff --git a/bin/zopen-split-patch b/bin/zopen-split-patch
--- a/bin/zopen-split-patch
+++ b/bin/zopen-split-patch
@@ -12,7 +12,7 @@ setupMyself()
   MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
   INCDIR="${MYDIR}/../include"
   if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
+    echo "Internal Error. Unable to find common.sh file to source." >&2
     exit 8
   fi
   . "${INCDIR}/common.sh"
