GPG Sign and verify pac file changes
The current PR enables the signing and verification of build.
The data in metadata.json i used for verification of signed files.

diff --git a/bin/zopen-build b/bin/zopen-build
--- a/bin/zopen-build
+++ b/bin/zopen-build
@@ -383,6 +383,7 @@ Option:
   --oci                 build and publish an OCI image to \$ZOPEN_IMAGE_REGISTRY.
   -s                    exec a shell before running configure. Useful when
                         manually building ports.
+  --signPax, -sp        This option signs the pax file.
   -v                    run in verbose mode.
   -vv                   run in very verbose mode (sets environment variables
                         V=1 and VERBOSE=1).
@@ -419,6 +420,7 @@ processOptions()
   getSourceOnly=false
   generatePax=false
   setActive=true
+  signPax=false
   forcePatchApply=false
   depsPath="${ZOPEN_PKGINSTALL}"
   forceUpgradeDeps=false
@@ -504,6 +506,9 @@ processOptions()
     "-s" | "--shell")
       startShell=true
       ;;
+    "-sp" | "--signPax")
+      signPax=true
+      ;;
     *)
       printError "Unknown option ${1} specified"
       ;;
@@ -511,6 +516,52 @@ processOptions()
     shift
   done
 }
+
+signPaxFile()
+{
+  # Paths to your files
+  PRIVATE_KEY="${ZOPEN_GPG_SECRET_KEY_FILE}"
+  PASSPHRASE_FILE="${GPG_SECRET_KEY_PASSPHRASE}"
+  FILE_TO_SIGN="${paxFileName}"
+  OUTPUT_SIGNATURE="${paxFileName}.asc"
+
+  # Create a temporary directory for GPG keyring
+  TMP_GPG_DIR="$HOME/tmp_gpg"
+  mkdir -p "$TMP_GPG_DIR"
+  chmod a+w "$TMP_GPG_DIR"
+
+  # Import the private key into the specified keyring files
+  printInfo "Importing private key..."
+  gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --secret-keyring "$TMP_GPG_DIR/secring.gpg" --batch --yes --import "$PRIVATE_KEY" > /dev/null 2>&1
+
+  # Verify that the key was imported successfully
+  printInfo "Checking if secret key is imported..."
+  gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --secret-keyring "$TMP_GPG_DIR/secring.gpg" --list-secret-keys > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+      printWarning "No secret key found. Signing aborted."
+      rm -rf "$TMP_GPG_DIR"
+      return 1
+  fi
+
+  # Sign the file
+  printInfo "Signing the file..."
+
+  gpg --armor --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --secret-keyring "$TMP_GPG_DIR/secring.gpg" --batch --verbose --pinentry-mode loopback --passphrase-file "$PASSPHRASE_FILE" --default-key YOUR_KEY_ID --output "$OUTPUT_SIGNATURE" --detach-sig "$FILE_TO_SIGN" > /dev/null 2>&1
+
+  if [ $? -ne 0 ]; then
+      printError "Error signing the file."
+      rm -rf "$TMP_GPG_DIR"
+      return 1
+  else
+      printInfo "File signed successfully. Signature saved to $OUTPUT_SIGNATURE."
+      SIGNATURE=$(jq -Rs . < ${OUTPUT_SIGNATURE})
+      echo "${SIGNATURE}"
+  fi
+
+  # Clean up the temporary keyring directory
+  rm -rf "$TMP_GPG_DIR"
+}
+
 
 loadBuildEnv()
 {
@@ -1662,7 +1713,7 @@ generateMetadataJSON()
     caveats="$(zopen_install_caveats)"
   fi
     
-  metadata_version_scheme="0.1" # Update if we add breaking changes to the json format
+  metadata_version_scheme="0.2" # Update if we add breaking changes to the json format
   cat <<zz > "${ZOPEN_INSTALL_DIR}/metadata.json"
 {
 "version_scheme": "${metadata_version_scheme}",
@@ -1832,13 +1883,42 @@ install()
 
       #TODO: Hack so that we can use coreutils md5sum without impacting builds
       ZOPEN_DEPS="${ZOPEN_DEPS} coreutils jq"
+      if [ -n "${signPax}" ]; then
+              if [ -z "${ZOPEN_GPG_SECRET_KEY_FILE}" ] || [ -z "${GPG_SECRET_KEY_PASSPHRASE}" ] || [ -z "${GPG_PUBLIC_KEY_PATH}" ]; then
+                        printWarning "GPG keyring environment variables are not set!"
+              else
+                ZOPEN_DEPS="${ZOPEN_DEPS} gpg"
+              fi
+      fi
       setDepsEnv
 
       pax_size=$(getPathSizeInBytes "${paxFileName}")
       md5sum=$(md5sum "${paxFileName}" | awk '{print $1}')
-      jq '.product |= . + { "pax": "'${ZOPEN_NAME}.${LOG_PFX}.zos.pax.Z'", "pax_size": "'${pax_size}'", "md5": "'${md5sum}'" }' "${ZOPEN_ROOT}/install/metadata.json" > "${ZOPEN_ROOT}/install/metadata.json.tmp"
+
+      if [ -n "${signPax}" ]; then
+        if [ -z "${ZOPEN_GPG_SECRET_KEY_FILE}" ] || [ -z "${GPG_SECRET_KEY_PASSPHRASE}" ] || [ -z "${GPG_PUBLIC_KEY_PATH}" ]; then
+                printWarning "GPG keyring environment variables are not set!"
+        else
+                signature=$(signPaxFile)
+                public_key=$(jq -Rs . < ${GPG_PUBLIC_KEY_PATH})
+        fi
+      fi
+
+      if [[ -n "${signature}" ]]; then
+         cat ${ZOPEN_INSTALL_DIR}/metadata.json
+         jq --arg pax "${ZOPEN_NAME}.${LOG_PFX}.zos.pax.Z" \
+            --arg pax_size "$pax_size" \
+            --arg md5 "$md5sum" \
+            --arg signature "$signature" \
+            --arg public_key "$public_key" \
+            '.product |= . + { "pax": $pax, "pax_size": $pax_size, "md5": $md5, "signature": $signature, "public_key": $public_key }' \
+            "${ZOPEN_ROOT}/install/metadata.json" > "${ZOPEN_ROOT}/install/metadata.json.tmp"
+      else
+        jq '.product |= . + { "pax": "'${ZOPEN_NAME}.${LOG_PFX}.zos.pax.Z'", "pax_size": "'${pax_size}'", "md5": "'${md5sum}'" }' "${ZOPEN_ROOT}/install/metadata.json" > "${ZOPEN_ROOT}/install/metadata.json.tmp"
+      fi
       mv "${ZOPEN_ROOT}/install/metadata.json.tmp" "${ZOPEN_ROOT}/install/metadata.json"
     fi
+
     if ${setActive}; then
       PROJECT_NAME="$(echo ${ZOPEN_NAME} | cut -d'-' -f1)"
       mergeIntoSystem "${PROJECT_NAME}" "${ZOPEN_INSTALL_DIR}" "${ZOPEN_ROOTFS}"
diff --git a/bin/zopen-install b/bin/zopen-install
--- a/bin/zopen-install
+++ b/bin/zopen-install
@@ -21,6 +21,76 @@ setupMyself()
 setupMyself
 checkWritable
 
+verifySignatureOfPax()
+{
+  echo "dh in verifySignatureOfPax , pwd = $PWD, extMetadataJSON= $extMetadataJSON, metadataFile = $metadataFile"
+  cat $extMetadataJSON
+  echo "dh DONE"
+  cat $metadataFile
+#  FILE_TO_VERIFY=$(jq -r '.product.pax' ${metadataFile})
+#  SIGNATURE=$(jq -r '.product.signature' ${metadataFile})
+#  PUBLIC_KEY=$(jq -r '.product.public_key' ${metadataFile})
+#
+#  # Extracting values and checking for errors
+FILE_TO_VERIFY=$(jq -r '.product.pax' "${metadataFile}")
+if [ $? -ne 0 ] || [ "${FILE_TO_VERIFY}" = "null" ] || [ -z "${FILE_TO_VERIFY}" ]; then
+    printError "Failed to extract 'pax' from ${metadataFile}" >&2
+    return 1
+fi
+
+SIGNATURE=$(jq -r '.product.signature' "${metadataFile}")
+if [ $? -ne 0 ] || [ "${SIGNATURE}" = "null" ] || [ -z "${SIGNATURE}" ]; then
+    printfError "Failed to extract 'signature' from ${metadataFile}" >&2
+    return 1
+fi
+
+PUBLIC_KEY=$(jq -r '.product.public_key' "${metadataFile}")
+if [ $? -ne 0 ] || [ "${PUBLIC_KEY}" = "null" ] || [ -z "${PUBLIC_KEY}" ]; then
+    printError "Failed to extract 'public_key' from ${metadataFile}" >&2
+    return 1
+fi
+
+
+  # Create a temporary directory for GPG keyring
+  TMP_GPG_DIR="$HOME/tmp_gpg_verify"
+  mkdir -p "$TMP_GPG_DIR"
+
+  SIGNATURE_FILE="signedfile.asc"
+  PUBLIC_KEY_FILE="scriptpubkey.asc"
+
+  # Remove surrounding double quotes and handle newlines
+  echo "$SIGNATURE" | sed 's/^"\(.*\)"$/\1/' | sed 's/\\n/\n/g' > "$SIGNATURE_FILE"
+  echo "$PUBLIC_KEY" | sed 's/^"\(.*\)"$/\1/' | sed 's/\\n/\n/g' > "$PUBLIC_KEY_FILE"
+
+  # Import the public key into the specified keyring files
+  printVerbose "Importing public key..."
+  gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --batch --yes --import "$PUBLIC_KEY_FILE" > /dev/null 2>&1
+
+  # Verify that the key was imported successfully
+  printVerbose "Checking if public key is imported..."
+  gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --list-keys > /dev/null 2>&1
+  if [ $? -ne 0 ]; then
+      printError "No public key found. Verification aborted."
+      rm -rf "$TMP_GPG_DIR"
+      return 1
+  fi
+
+  # Verify the signature
+  printVerbose "Verifying the signature..."
+  gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --verify "$SIGNATURE_FILE" "$FILE_TO_VERIFY"
+  if gpg --no-default-keyring --keyring "$TMP_GPG_DIR/pubring.kbx" --verify "$SIGNATURE_FILE" "$FILE_TO_VERIFY" 2>&1 | grep -q "Good signature from"; then
+     printInfo "${NC}${GREEN}Signature verified successfully: ${name}${NC}"
+     return 0
+  else
+     printError "Verification failed"
+     return 2
+  fi
+
+  # Clean up the temporary directory/files
+  rm -rf "${SIGNATURE_FILE}"
+  rm -rf "${PUBLIC_KEY_FILE}"
+  rm -rf "${TMP_GPG_DIR}"
+}
 printSyntax()
 {
   args=$*
@@ -383,11 +453,33 @@ handlePackageInstall()
       rm -rf "${baseinstalldir}/${installdirname}"
     fi
 
-    if ! runLogProgress "pax -rf ${pax} -p p ${paxredirect} ${redirectToDevNull}" "Expanding ${pax}" "Expanded"; then
-      printWarning "Errors unpaxing, package directory state unknown."
-      printInfo "Use zopen alt to select previous version."
-      continue
+    extractPax=true
+
+    metadataVersion=$(jq -r '.version_schema' "${metadataFile}" 2>/dev/null)
+    if [ -n "${metadataVersion}" ]; then
+      printf "${NC}${HEADERCOLOR}${BOLD}${name}${NC}:\n ${installCaveat}\n" >> ${caveatsFile}
     fi
+
+    #if [ "${skipverify}" = false ]; then
+    if (( $(echo "$metadataVersion > 0.1" | bc -l) )) && [ "$skipverify" = "false" ]; then
+           printVerbose "Verify sign for version '${installdirname}'"
+           printVerbose "Verify sign for metadataFile '${metadataFile}'"
+           cat ${metadataFile}
+           verifySignatureOfPax
+           ret_val=$?
+           if [ $ret_val -eq 2 ]; then
+                   printInfo "dh extractPax true here -1 "
+                   extractPax=false;
+           fi
+    fi
+    if [ "$extract" = true ]; then
+       if ! runLogProgress "pax -rf ${pax} -p p ${paxredirect} ${redirectToDevNull}" "Expanding ${pax}" "Expanded"; then
+           printWarning "Errors unpaxing, package directory state unknown."
+           printInfo "Use zopen alt to select previous version."
+       continue
+       fi
+    fi
+
     if ${localInstall}; then
       rm -f "${pax}"
     fi
