Update help output with new option --ai

diff --git a/bin/zopen-generate b/bin/zopen-generate
--- a/bin/zopen-generate
+++ b/bin/zopen-generate
@@ -35,6 +35,7 @@ printSyntax()
 {
   echo "zopen-generate will generate a zopen compatible project" >&2
   echo "Syntax: zopen-generate" >&2
+  echo "zopen build --ai will run with tinyllama model via LocalAI, zopen build will send error to the model and the model will provide what patch we need to do." >&2
 }
 
 if [ $# -eq 1 ]; then
diff --git a/bin/zopen-md2man b/bin/zopen-md2man
--- a/bin/zopen-md2man
+++ b/bin/zopen-md2man
@@ -24,6 +24,7 @@ printSyntax()
 {
   echo "zopen-md2man will generate man pages from markdown (to be removed)" >&2
   echo "Syntax: zopen-md2man" >&2
+  echo "zopen build --ai will run with tinyllama model via LocalAI, zopen build will send error to the model and the model will provide what patch we need to do." >&2
 }
 
 if [[ $# -eq 1 ]]; then
