Revert "Format zopen scripts"
This reverts commit 0dc2d71887306b8736a5fcdec1e8c0610622bef2.

diff --git a/bin/zopen-compute-builddeps b/bin/zopen-compute-builddeps
--- a/bin/zopen-compute-builddeps
+++ b/bin/zopen-compute-builddeps
@@ -8,14 +8,14 @@
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -53,7 +53,7 @@ rootpkg="$1"
 
 tmpdir="/tmp/blddep_$$"
 
-if ! mkdir "${tmpdir}"; then
+if ! mkdir "${tmpdir}" ; then
   echo "Unable to create temporary directory for computing transitive closure" >&2
   syntax
 fi
@@ -71,8 +71,8 @@ changed=true
 while ${changed}; do
   changed=false
   for pkg in ${deps}; do
-    if ! [[ -v scanned["${pkg}"] ]]; then
-      if ! git clone "git@github.com:ZOSOpenTools/${pkg}port.git"; then
+    if ! [[ -v scanned["${pkg}"] ]] ; then
+      if ! git clone "git@github.com:ZOSOpenTools/${pkg}port.git" ; then
         echo "Unable to clone package ${pkg}" >&2
         exit 4
       else
@@ -88,7 +88,7 @@ while ${changed}; do
         echo "${pkg} needs ${newpkgs}"
       fi
       for newpkg in ${newpkgs}; do
-        if ! [[ -v scanned["${newpkg}"] ]]; then
+        if ! [[ -v scanned["${newpkg}"] ]] ; then
           deps="${deps} ${newpkg}"
         fi
       done
diff --git a/bin/zopen-help2man b/bin/zopen-help2man
--- a/bin/zopen-help2man
+++ b/bin/zopen-help2man
@@ -4,14 +4,14 @@
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -45,7 +45,7 @@ else
 fi
 
 set -e
-export rootdir="$(cd "$MYDIR/../" && dirname "$PWD" >/dev/null 2>&1 && pwd -P)"
+export rootdir="$( cd "$MYDIR/../" && dirname "$PWD" >/dev/null 2>&1 && pwd -P )"
 
 help2manopts="--no-discard-stderr -N"
 
@@ -67,20 +67,23 @@ for tooldir in ${tooldirs}; do
   for tool in $tooldir/zopen*; do
     basetool=$(basename ${tool})
     help2man ${help2manopts} "${tool}" >"${mandir}/${basetool}.1"
-    if $("${tool}" --help >/dev/null 2>&1); then
+    if  $( "${tool}" --help >/dev/null 2>&1 ) ; then
       # Tool has implemented --help
-      if $("${tool}" --version >/dev/null 2>&1); then
+      if  $( "${tool}" --version >/dev/null 2>&1 ) ; then
         echo "${basetool}"
-      else
+      else 
         echo "${tool} supports --help but not --version options. man page generation skipped." >&2
       fi
-    else
+    else 
       # Tool has NOT implemented --help
-      if $("${tool}" --version >/dev/null 2>&1); then
+      if  $( "${tool}" --version >/dev/null 2>&1 ) ; then
         echo "${tool} does not support --help but does support man page generation skipped." >&2
-      else
+      else 
         echo "${tool} does not support --help nor --version options. man page generation skipped." >&2
       fi
     fi
   done
 done
+
+
+
diff --git a/bin/zopen-init b/bin/zopen-init
--- a/bin/zopen-init
+++ b/bin/zopen-init
@@ -6,36 +6,36 @@ ZOPEN_DONT_PROCESS_CONFIG=1
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
-printSyntax()
+printSyntax() 
 {
   args=$*
   echo "zopen init will initialize the zopen filesystem and configuration (create a <root-dir>/etc/zopen-config file)" >&2
   echo "Syntax: zopen init [<option>] [<root-dir>]" >&2
   echo "  where <option> can be one or more of:" >&2
   echo "  -f <type>: virtual filesystem location for package management; packages will be installed to this location under the <root-dir>" >&2
-  echo "      usrlclz - /usr/local/zopen (default)" >&2
+  echo "      usrlclz - /usr/local/zopen (default)" >&2 
   echo "      zopen - /usr/zopen" >&2
   echo "      prod - zopen standard" >&2
   echo "      ibm  - /usr/lpp" >&2
-  echo "      fhs  - File Hierarchical Standard (/opt)" >&2
-  echo "      usrlcl - /usr/local" >&2
+  echo "      fhs  - File Hierarchical Standard (/opt)"  >&2
+  echo "      usrlcl - /usr/local">&2
   echo "  --re-init: re-initialize a previous installation (if present).  Re-initializing over a previous installation will re-use existing package structures and configurations." >&2
   echo "  --clone: clones the current installation to a different location" >&2
   echo "  --append-to-profile: appends sourcing of zopen-config to .profile" >&2
-  echo "  --releaseline-dev: whether to globally enable Development packages" >&2
-  echo "  --yes|-y: automatically answer yes to prompts." >&2
+  echo "  --releaseline-dev: whether to globally enable Development packages" >&2 
+  echo "  --yes|-y: automatically answer yes to prompts."  >&2
   echo "  -v: run in verbose mode" >&2
   echo "  -?|-h|--help: display help" >&2
 }
@@ -52,72 +52,73 @@ releaselineDev=false
 fslayout="usrlclz"
 while [ $# -gt 0 ]; do
   case "$1" in
-  "-f" | "--fs-layout")
-    fslayout=$2
-    shift
-    ;;
-  "--re-init")
-    reinitExisting=true
-    ;;
-  "--clone")
-    clone=true
-    ;;
-  "--append-to-profile")
-    appendToProfile=true
-    ;;
-  "--releaseline-dev")
-    releaselineDev=true
-    ;;
-  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
-    printSyntax "${args}"
-    exit 0
-    ;;
-  "-v" | "--v" | "-verbose" | "--verbose")
-    verbose=true
-    ;;
-  "--version")
-    zopen --version $ME
-    exit 0
-    ;;
-  "--debug")
-    debug=true
-    ;;
-  "--yes" | "-y")
-    yesToPrompts=true # Automatically answer 'yes' to any questions
-    ;;
-  *)
-    rootfs=$1
-    ;;
+    "-f" | "--fs-layout" )
+      fslayout=$2
+      shift
+      ;;
+    "--re-init" )
+      reinitExisting=true
+      ;;
+    "--clone" )
+      clone=true
+      ;;
+    "--append-to-profile" )
+      appendToProfile=true
+      ;;
+    "--releaseline-dev" )
+      releaselineDev=true
+      ;;
+    "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
+      printSyntax "${args}"
+      exit 0
+      ;;
+    "-v" | "--v" | "-verbose" | "--verbose")
+      verbose=true
+      ;;
+    "--version")
+      zopen --version $ME
+      exit 0
+      ;;
+    "--debug") 
+      debug=true
+      ;;
+    "--yes" | "-y")
+      yesToPrompts=true  # Automatically answer 'yes' to any questions
+      ;;
+    *)
+      rootfs=$1;
+      ;;
   esac
-  shift
+  shift;
 done
 case "$fslayout" in
-fhs | ibm | prod | zopen | usrlcl | usrlclz) ;;
-*)
-  printError "${NC}${RED}The filesystem layout $fslayout is unrecognised"
+  fhs|ibm|prod|zopen|usrlcl|usrlclz)
   ;;
+  *)
+    printError "${NC}${RED}The filesystem layout $fslayout is unrecognised"
+    ;;
 esac
 
 printHeader "Initialize zopen framework"
 
 case "$fslayout" in
-"usrlclz")
-  zopen_pkginstall="usr/local/zopen"
+  "usrlclz")
+    zopen_pkginstall="usr/local/zopen"
   ;;
-"usrlcl")
-  zopen_pkginstall="usr/local"
+  "usrlcl")
+    zopen_pkginstall="usr/local"
   ;;
-"fhs")
-  zopen_pkginstall="opt"
+  "fhs")
+    zopen_pkginstall="opt"
   ;;
-"ibm")
-  zopen_pkginstall="usr/lpp"
+  "ibm")
+    zopen_pkginstall="usr/lpp"
   ;;
-"prod")
-  zopen_pkginstall="prod"
+  "prod")
+    zopen_pkginstall="prod"
   ;;
-"zopen")
-  zopen_pkginstall="usr/zopen"
+  "zopen")
+    zopen_pkginstall="usr/zopen"
   ;;
 esac
 
@@ -166,9 +167,9 @@ printInfo "- Packages will be installed and maintained under the directory struc
 if ! $yesToPrompts; then
   while true; do
     printInfo "Do you want to continue? [y/n]"
-    read continueInstall </dev/tty
+    read continueInstall < /dev/tty
     if [ "y" = "${continueInstall}" ]; then
-      break
+      break;
     fi
     if [ "n" = "${continueInstall}" ]; then
       printInfo "Exiting..."
@@ -188,9 +189,7 @@ if [ -f "$configFile" ]; then
       printWarning "- Existing configuration file found; re-initializing might lose access to previously installed packages. Continue (y/n)?"
       reinit=$(getInput)
     fi
-    if $reinitExisting || {
-      [ -n "$reinit" ] && [ "y" = "${reinit}" ]
-    }; then
+    if $reinitExisting || { [ -n "$reinit" ] && [ "y" = "${reinit}" ]; }; then
       printInfo "- Re-initializing; removing existing zopen-config"
       rmrf=$(rm -rf "$configFile")
     else
@@ -203,8 +202,8 @@ fi
 if ! $clone; then
   printInfo "Checking for existence of specified root: '$rootfs'"
   [ -e "$rootfs" ] || mkdir -p "$rootfs" || printError "Unable to create zopen root filesystem at '$rootfs'"
-  [ -d "$rootfs" ] || printError "Specified location '$rootfs' is not a directory. Unable to access root file system at '$rootfs'; check permissions"
-  [ -w "$rootfs" ] || printError "Unable to write to root file system at '$rootfs'; check permissions"
+  [ -d "$rootfs" ] || printError "Specified location '$rootfs' is not a directory. Unable to access root file system at '$rootfs'; check permissions"  
+  [ -w "$rootfs" ] || printError "Unable to write to root file system at '$rootfs'; check permissions"  
 
   printInfo "- Populating standard file system"
   [ -e "$rootfs/bin" ] || mkdir -p "$rootfs/bin"
@@ -216,15 +215,15 @@ if ! $clone; then
   [ -e "$rootfs/var/cache/zopen" ] || mkdir -p "$rootfs/var/cache/zopen"
   [ -e "$rootfs/var/log" ] || mkdir -p "$rootfs/var/log"
   [ -e "$rootfs/var/tmp" ] || mkdir -p "$rootfs/var/tmp"
-
+  
   printInfo "- Creating path for bootstrap files"
   [ -e "$rootfs/boot" ] || mkdir -p "$rootfs/boot"
-
+  
   printInfo "- Creating symbolic path for prod redirect files"
   [ -e "$rootfs/usr/share/zopen/boot" ] || ln -s "$rootfs/boot" "$rootfs/usr/share/zopen/boot"
   [ -e "$rootfs/etc/zopen" ] || mkdir -p "$rootfs/etc/zopen"
-  echo "$zopen_pkginstall" >"$rootfs/etc/zopen/fstype"
-
+  echo "$zopen_pkginstall" > "$rootfs/etc/zopen/fstype"
+  
   [ -e "$rootfs/$zopen_pkginstall" ] || mkdir -p "$rootfs/$zopen_pkginstall"
   [ -e "$rootfs/usr/share/zopen/prod" ] || ln -s "$rootfs/$zopen_pkginstall" "$rootfs/usr/share/zopen/prod"
 else
@@ -237,35 +236,35 @@ else
 fi
 
 if [ "$ZOPEN_PKGINSTALL" = "$rootfs" ]; then
-  printWarning "Package install location is the zopen root location; this is not recommended. Continue (y/n)"
-  pkgoverlaysrootfs=$(getInput)
-  if [ -n "$pkgoverlaysrootfs" ] && [ "y" = "${pkgoverlaysrootfs}" ]; then
-    printInfo "- Continuing. Packages will be installed into the zopen root location: $rootfs"
-  else
-    printWarning "- Stopping. Existing configuration will be preserved"
-    exit 8
-  fi
+   printWarning "Package install location is the zopen root location; this is not recommended. Continue (y/n)"
+   pkgoverlaysrootfs=$(getInput)
+   if [ -n "$pkgoverlaysrootfs" ] && [ "y" = "${pkgoverlaysrootfs}" ]; then
+     printInfo "- Continuing. Packages will be installed into the zopen root location: $rootfs"
+   else
+     printWarning "- Stopping. Existing configuration will be preserved"
+     exit 8
+   fi
 fi
 
-ZOPEN_CA_DIR="etc/pki/tls/certs" # Mimic location on some Linux distributions
+ZOPEN_CA_DIR="etc/pki/tls/certs"  # Mimic location on some Linux distributions
 certFileName="cacert.pem"
 if ! $clone; then
-  printInfo "- Creating path for certificate lookups"
-  [ -e "$rootfs/$ZOPEN_CA_DIR" ] || mkdir -p "$rootfs/$ZOPEN_CA_DIR"
+    printInfo "- Creating path for certificate lookups"
+    [ -e "$rootfs/$ZOPEN_CA_DIR" ] || mkdir -p "$rootfs/$ZOPEN_CA_DIR"
 fi
 
 # Save the configuration to the file - overwrite any existing file with the title initially
-echo "# z/OS Open Tools Configuration file" >"$configFile"
-echo "# Main root location for the zopen installation; can be changed if the " >>"$configFile"
-echo "# underlying root location is copied/moved elsewhere as locations are " >>"$configFile"
-echo "# relative to this envvar value" >>"$configFile"
-echo "ZOPEN_ROOTFS=\"$rootfs\"" >>"$configFile"
-echo "export ZOPEN_ROOTFS" >>"$configFile"
-echo "configStartTime=\$SECONDS" >>"$configFile"
-echo "zot=\"z/OS Open Tools\"" >>"$configFile"
+echo "# z/OS Open Tools Configuration file" > "$configFile"
+echo "# Main root location for the zopen installation; can be changed if the " >> "$configFile"
+echo "# underlying root location is copied/moved elsewhere as locations are " >> "$configFile"
+echo "# relative to this envvar value" >> "$configFile"
+echo "ZOPEN_ROOTFS=\"$rootfs\"" >> "$configFile"
+echo "export ZOPEN_ROOTFS" >> "$configFile"
+echo "configStartTime=\$SECONDS" >> "$configFile"
+echo "zot=\"z/OS Open Tools\"" >> "$configFile"
 
 # Add the profiled processing first so the zopen paths are added first
-cat <<EOF >>"$configFile"
+cat << EOF >>  "$configFile"
 # Temporary file location
 for tmp in "\$TMPDIR" "\$TMP" /tmp
 do
@@ -388,16 +387,16 @@ else
   export ZOPEN_ROOTFS="$rootfs"
 
   # Generate any system values that can be user changed
-  echo "15" >"$rootfs/etc/zopen/rm_fileprocs"
+  echo "15" > "$rootfs/etc/zopen/rm_fileprocs"
 
   if $releaselineDev; then
     releaseLine="DEV"
-    printInfo "- Configured zopen to use development (DEV) releaseline packages where available"
+    printInfo "- Configured zopen to use development (DEV) releaseline packages where available" 
   else
     releaseLine="STABLE"
     printInfo "- Configured zopen to use stable releaseline packages"
   fi
-  echo "$releaseLine" >"$rootfs/etc/zopen/releaseline"
+  echo "$releaseLine" > "$rootfs/etc/zopen/releaseline"
 
   printInfo "- Check for shipped curl pax"
   curlpax="packages/curl-8.1.2.20230707_145137.zos.pax.Z"
@@ -481,7 +480,7 @@ else
   else
     printError "- Could not access '$certFileName' in '$ZOPEN_ROOTFS/$ZOPEN_CA_DIR'"
   fi
-
+  
   # Need to source the .env file from within the actual curl directory and cannot
   # spawn sub-process otherwise no access to environment from this script so run inline
   printVerbose "Sourcing environment to trigger any setup required for packages"
@@ -491,7 +490,7 @@ else
   curwd=$PWD
   cd "$rootfs/boot/$curldir/" || printError "Could not access boot curl directory. Re-run 'zopen init' to retry"
   . ./.env
-  cd "$curwd" || printError "Could not change to $curwd. Re-run 'zopen init' to retry"
+  cd "$curwd"  || printError "Could not change to $curwd. Re-run 'zopen init' to retry"
 
   jqdir="$(ls $rootfs/boot | grep jq)"
   [ -e "$rootfs/boot/$jqdir" ] || printError "Could not locate jq for bootstrap. Re-run 'zopen init' to retry"
@@ -499,8 +498,8 @@ else
   curwd=$PWD
   cd "$rootfs/boot/$jqdir/" || printError "Could not access boot curl directory. Re-run 'zopen init' to retry"
   . ./.env
-  cd "$curwd" || printError "Could not change to $curwd. Re-run 'zopen init' to retry"
-
+  cd "$curwd"  || printError "Could not change to $curwd. Re-run 'zopen init' to retry"
+  
   printInfo "- Updating CA cert"
   ZOPEN_CA="$ZOPEN_ROOTFS/$ZOPEN_CA_DIR"
   mkdir -p "$ZOPEN_CA"
@@ -521,7 +520,7 @@ else
   if $appendToProfile; then
     if ! grep -q ". $rootfs/etc/zopen-config" "$HOME/.profile"; then
       printVerbose "Line not present (grep returned non-0)"
-      cat <<EOF >>"$HOME/.profile"
+  cat << EOF >>  "$HOME/.profile"
   [ -e "$rootfs/etc/zopen-config" ] && . $rootfs/etc/zopen-config
 EOF
     fi
diff --git a/bin/zopen-install b/bin/zopen-install
--- a/bin/zopen-install
+++ b/bin/zopen-install
@@ -5,19 +5,19 @@
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
-printSyntax()
+printSyntax() 
 {
   args=$*
   echo "zopen install is a utility to download/install a z/OS Open Tools package."
@@ -25,17 +25,17 @@ printSyntax()
   echo "  where <option> may be one or more of:" >&2
   echo "  --help: print this help." >&2
   echo "  --version: print version" >&2
-  echo "  -u|--update|--upgrade: updates installed z/OS Open Tools packages." >&2
-  echo "  --install-or-upgrade: installs the package if not installed, or upgrades the package if installed." >&2
-  echo "  --reinstall: reinstall already installed z/OS Open Tools packages." >&2
+  echo "  -u|--update|--upgrade: updates installed z/OS Open Tools packages."  >&2
+  echo "  --install-or-upgrade: installs the package if not installed, or upgrades the package if installed."  >&2
+  echo "  --reinstall: reinstall already installed z/OS Open Tools packages."  >&2
   echo "  --nosymlink: do not integrate into filesystem through symlink redirection. " >&2
   echo "  --release-line <stable|dev>: the release line to build off of." >&2
-  echo "  --no-deps: do not install dependencies." >&2
-  echo "  --cache-only: do not install dependencies." >&2
-  echo "  --no-set-active: do not change the pinned version" >&2
-  echo "  --skip-upgrade: do not upgrade." >&2
-  echo "  --yes|-y: automatically answer yes to prompts." >&2
-  echo "  --select: select a version to install." >&2
+  echo "  --no-deps: do not install dependencies."  >&2
+  echo "  --cache-only: do not install dependencies."  >&2
+  echo "  --no-set-active: do not change the pinned version"  >&2
+  echo "  --skip-upgrade: do not upgrade."  >&2
+  echo "  --yes|-y: automatically answer yes to prompts."  >&2
+  echo "  --select: select a version to install."  >&2
   echo "  -v: run in verbose mode" >&2
   echo "  --download-only: download package to current directory" >&2
   echo "  --local-install: download and unpackage to current directory" >&2
@@ -57,8 +57,7 @@ installDependencies()
   skipupgrade=$skipupgrade_lcl
 )
 
-handlePackageInstall()
-{
+handlePackageInstall(){
 
   fullname="$1"
   printVerbose "Name to install: $fullname, parsing any version ('=') or tag ('%') has been specified"
@@ -100,7 +99,7 @@ handlePackageInstall()
   else
     printVerbose "No current releaseline for package"
   fi
-
+  
   releaseMetadata=""
   downloadURL=""
   # Options where the user explicitly sets a version/tag/releaseline currently ignore any configured release-line,
@@ -134,7 +133,7 @@ handlePackageInstall()
     valid=false
     while ! $valid; do
       echo "Enter version to install (0-$i): "
-      read selection </dev/tty
+      read selection < /dev/tty
       if [[ ! -z $(echo "$selection" | sed -e 's/[0-9]*//') ]]; then
         echo "Invalid input, must be a number between 0 and $i"
       elif [ "$selection" -ge 0 ] && [ "$selection" -le "$i" ]; then
@@ -144,7 +143,7 @@ handlePackageInstall()
     printVerbose "Selecting item $selection from array"
     releaseMetadata="$(/bin/printf "%s" "$releases" | jq -e -r ".[$selection]")"
 
-  elif [ ! -z "$releaseLine" ]; then
+  elif [ ! -z "$releaseLine" ]; then  
     printVerbose "Install from release line '$releaseLine' specified"
     validatedReleaseLine=$(validateReleaseLine "$releaseLine")
     if [ -z "$validatedReleaseLine" ]; then
@@ -157,13 +156,13 @@ handlePackageInstall()
     if [ $? -ne 0 ]; then
       printError "Could not find release-line $releaseLine for repo: $repo"
     fi
-
+    
   else
     printVerbose "No explicit version/tag/releaseline, checking for pre-existing package&releaseline"
     if [ -n "$installedReleaseLine" ]; then
       printVerbose "Found existing releaseline '$installedReleaseLine', restricting to only that releaseline"
-      validatedReleaseLine="$installedReleaseLine" # Already validated when stored
-    else
+      validatedReleaseLine="$installedReleaseLine"  # Already validated when stored
+    else 
       printVerbose "Checking for system-configured releaseline"
       sysrelline=$(cat "$ZOPEN_ROOTFS/etc/zopen/releaseline" | awk ' {print toupper($1)}')
       printVerbose "Validating value: $sysrelline"
@@ -178,13 +177,13 @@ handlePackageInstall()
       fi
     fi
     # We have some situations that could arise
-    # 1. the port being installed has no releaseline tagging yet (ie. no releases tagged STABLE_* or DEV_*)
-    # 2. system is configured for STABLE but only has DEV stream available
-    # 3. system is configured for DEV but only has DEV stream available
-    # 4. the port being installed has got full releaseline tagging
-    # The issue could arise that the user has switched the system from DEV->STABLE or vice-versa so package
-    # stream mismatches could arise but in normal case, once a package is installed [that has releaseline tagging]
-    # then that specific releaseline will be used
+      # 1. the port being installed has no releaseline tagging yet (ie. no releases tagged STABLE_* or DEV_*)
+      # 2. system is configured for STABLE but only has DEV stream available
+      # 3. system is configured for DEV but only has DEV stream available
+      # 4. the port being installed has got full releaseline tagging
+      # The issue could arise that the user has switched the system from DEV->STABLE or vice-versa so package
+      # stream mismatches could arise but in normal case, once a package is installed [that has releaseline tagging]
+      # then that specific releaseline will be used
     printVerbose "Finding any releases tagged with $validatedReleaseLine and getting the first (newest/latest)"
     releaseMetadata="$(/bin/printf "%s" "$releases" | jq -e -r '. | map(select(.tag_name | startswith("'$validatedReleaseLine'")))[0]')"
     printVerbose "Use quick check for asset to check for existence of metadata"
@@ -227,7 +226,7 @@ handlePackageInstall()
   fi
 
   tagname=$(/bin/printf "%s" "$releaseMetadata" | jq -e -r ".tag_name" | sed "s/\([^_]*\)_.*/\1/")
-  installedReleaseLine=$(validateReleaseLine "$tagname")
+  installedReleaseLine=$(validateReleaseLine "$tagname" )
 
   downloadURL=$(/bin/printf "%s" "$asset" | jq -e -r '.url')
   size=$(/bin/printf "%s" "$asset" | jq -e -r '.expanded_size')
@@ -236,7 +235,7 @@ handlePackageInstall()
     printError "Unable to determine download location for ${name}"
   fi
   downloadFile=$(basename "$downloadURL")
-  downloadFileVer=$(echo "$downloadFile" | sed -E 's/.*-(.*)\.zos\.pax\.Z/\1/')
+  downloadFileVer=$(echo "$downloadFile" |sed -E 's/.*-(.*)\.zos\.pax\.Z/\1/')
   printVerbose "Downloading port from URL: $downloadURL to file: $downloadFile (ver=$downloadFileVer)"
 
   if $downloadOnly; then
@@ -246,7 +245,7 @@ handlePackageInstall()
     if [ "${downloadFileVer}" = "${originalFileVersion}" ]; then
       if ! $reinstall; then
         printInfo "${NC}${GREEN}Package ${name} is already installed at the requested version: ${downloadFileVer}${NC}"
-        return
+        return;
       fi
       printInfo "- Reinstalling version '$downloadFileVer' of ${name}..."
     fi
@@ -258,13 +257,13 @@ handlePackageInstall()
         printVerbose "Package ${name} was not installed so not upgrading but installing"
       elif $upgradeInstalled; then
         printError "Package ${name} can not be upgraded as it is not installed!"
-        continue
+        continue;
       fi
       unInstallOldVersion=false
       printInfo "- Installing ${name}..."
     elif $skipupgrade; then
       printInfo "Package ${name} has a newer release '${downloadFileVer}' but explicitly skipping"
-      continue
+      continue;
     elif ! $setactive; then
       printVerbose "Current version '${originalFileVersion}' will remain active"
       unInstallOldVersion=false
@@ -273,7 +272,7 @@ handlePackageInstall()
       if [ -e "${rootInstallDir}/${name}/${name}/.pinned" ]; then
         printWarning "- Version '${originalFileVersion}' has been pinned; upgrade to '${downloadFileVer}' skipped"
         syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_PACKAGE,$CAT_INSTALL" "DOWNLOAD" "handlePackageInstall" "Attempt to change pinned package '${name}' skipped"
-        continue
+        continue;
       else
         printInfo "- Replacing ${name} version '${originalFileVersion}' with '${downloadFileVer}'"
         unInstallOldVersion=true
@@ -309,9 +308,9 @@ handlePackageInstall()
 
     if ! runAndLog "curlCmd -L '${downloadURL}' -O ${redirectToDevNull}"; then
       printError "Could not download from ${downloadURL}. Correct any errors and potentially retry"
-      continue
+      continue;
     fi
-    $killph 2>/dev/null # if the timer is not running, the kill will fail
+    $killph 2>/dev/null  # if the timer is not running, the kill will fail
     syslog "$ZOPEN_LOG_PATH/audit.log" "$LOG_A" "$CAT_NETWORK,$CAT_PACKAGE,$CAT_FILE" "DOWNLOAD" "handlePackageInstall" "Downloaded remote file '$pax'"
   fi
   if [ ! -f "${pax}" ]; then
@@ -344,9 +343,9 @@ handlePackageInstall()
     if ! $yesToPrompts; then
       while true; do
         printInfo "Do you want to continue? [y/n]"
-        read continueInstall </dev/tty
+        read continueInstall < /dev/tty
         if [ "y" = "${continueInstall}" ]; then
-          break
+          break;
         fi
         if [ "n" = "${continueInstall}" ]; then
           mutexFree "zopen"
@@ -357,15 +356,15 @@ handlePackageInstall()
     fi
 
     printVerbose "Check for existing directory for version '$installdirname'"
-    if [ -d "$baseinstalldir/$installdirname" ]; then
+    if [ -d "$baseinstalldir/$installdirname" ]; then 
       printInfo "- Clearing existing directory and contents"
       rm -rf "$baseinstalldir/$installdirname"
     fi
 
     if ! runLogProgress "pax -rf $pax -p p $paxredirect ${redirectToDevNull}" "Expanding $pax" "Expanded"; then
       printWarning "Errors unpaxing, package directory state unknown"
-      printInfo "Use zopen alt to select previous version"
-      continue
+      printInfo    "Use zopen alt to select previous version"
+      continue;
     fi
     if $localInstall; then
       rm -f "${pax}"
@@ -378,26 +377,26 @@ handlePackageInstall()
       fi
       if ! ln -s "$baseinstalldir/$installdirname" "$baseinstalldir/$name/${name}"; then
         printError "Could not create symbolic link name"
-      fi
-    fi
+      fi 
+    fi 
 
     printVerbose "Adding version '${downloadFileVer}' to info file"
     # Add file version information as a .releaseinfo file
-    echo "$downloadFileVer" >"${baseinstalldir}/$installdirname/.releaseinfo"
+    echo "$downloadFileVer" > "${baseinstalldir}/$installdirname/.releaseinfo"
 
     # Check for a .version file from the pax - if present good, if not
     # generate one from the file name as the tag isn't granular enough to really
     # be used in dependency checks
     if [ ! -f "${baseinstalldir}/$installdirname/.version" ]; then
-      echo "$downloadFileVer" >"${baseinstalldir}/$installdirname/.version"
+      echo "$downloadFileVer" > "${baseinstalldir}/$installdirname/.version"
     fi
 
     printVerbose "Adding releaseline '$installedReleaseLine' metadata to ${baseinstalldir}/$installdirname/.releaseline"
-    echo "$installedReleaseLine" >"${baseinstalldir}/$installdirname/.releaseline"
+    echo "$installedReleaseLine" > "${baseinstalldir}/$installdirname/.releaseline"
 
     if $setactive; then
       if ! $nosymlink; then
-        mergeIntoSystem "$name" "${baseinstalldir}/$installdirname" "$ZOPEN_ROOTFS"
+        mergeIntoSystem "$name" "${baseinstalldir}/$installdirname" "$ZOPEN_ROOTFS" 
         misrc=$?
         printVerbose "The merge completed with: $misrc"
       fi
@@ -406,7 +405,7 @@ handlePackageInstall()
       if [ -f ${baseinstalldir}/${name}/${name}/.env -o -f ${baseinstalldir}/${name}/${name}/.appenv ]; then
         printInfo "- .env file found, adding to profiled processing"
         mkdir -p "$ZOPEN_ROOTFS/etc/profiled/$name"
-        cat <<EOF >"$ZOPEN_ROOTFS/etc/profiled/$name/dotenv"
+        cat << EOF > "$ZOPEN_ROOTFS/etc/profiled/$name/dotenv"
 curdir=\$(pwd)
 cd "$baseinstalldir/$name/$name" >/dev/null 2>&1
 # If .appenv exists, source it as it's quicker
@@ -436,7 +435,7 @@ EOF
     fi
 
     if $doNotInstallDeps; then
-      printInfo "- Skipping dependency installation"
+        printInfo "- Skipping dependency installation"
     elif $reinstall; then
       printVerbose "- Reinstalling so no dependency reinstall (unless explicitly listed)"
     else
@@ -496,69 +495,69 @@ yesToPrompts=false
 chosenRepos=""
 while [ $# -gt 0 ]; do
   case "$1" in
-  "-u" | "--update" | "-update" | "-upgrade" | "--upgrade")
-    upgradeInstalled=true # Upgrade packages
-    ;;
-  "-r" | "-reinstall" | "--reinstall")
-    reinstall=true # If package already installed, reinstall
-    ;;
-  "--install-or-upgrade")
-    installOrUpgrade=true # Upgrade package or install if not present
-    ;;
-  "--local-install")
-    localInstall=true # Install the package into current directory
-    ;;
-  "--no-symlink")
-    nosymlink=true # Do not mesh the package into the file system; leave as stand-alone
-    ;;
-  "--no-deps")
-    doNotInstallDeps=true
-    ;;
-  "--cache-only")
-    cacheOnly=true # Download remote pax file to cache only (no install)
-    ;;
-  "--release-line")
-    shift
-    releaseLine=$(echo "$1" | awk '{print toupper($0)}')
-    ;;
-  "--yes" | "-y")
-    yesToPrompts=true # Automatically answer 'yes' to any questions
-    ;;
-  "--download-only")
-    downloadOnly=true # Download remote pax file to current directory only
-    ;;
-  "--no-set-active")
-    setactive=false # Install package as normal but keep existing installation as active
-    ;;
-  "--skip-upgrade")
-    skipupgrade=true # Do not upgrade any packages
-    ;;
-  "--all")
-    all=true # Install all packages
-    ;;
-  "--select")
-    selectVersion=true # Display a selction table to allow version picking
-    ;;
-  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
-    printSyntax "${args}"
-    exit 0
-    ;;
-  "--debug")
-    verbose=true
-    debug=true
-    ;;
-  "-v" | "--v" | "-verbose" | "--verbose")
-    verbose=true
-    ;;
-  "--version")
-    zopen --version $ME
-    exit 0
-    ;;
-  *)
-    chosenRepos="$chosenRepos $1"
-    ;;
+    "-u" | "--update" | "-update" | "-upgrade" | "--upgrade")
+      upgradeInstalled=true  # Upgrade packages
+      ;;
+    "-r" | "-reinstall" | "--reinstall")
+      reinstall=true  # If package already installed, reinstall
+      ;;
+    "--install-or-upgrade")
+      installOrUpgrade=true  # Upgrade package or install if not present
+      ;;
+    "--local-install")
+      localInstall=true # Install the package into current directory
+      ;;
+    "--no-symlink")
+      nosymlink=true  # Do not mesh the package into the file system; leave as stand-alone
+      ;;
+    "--no-deps")
+      doNotInstallDeps=true
+      ;;
+    "--cache-only")
+      cacheOnly=true  # Download remote pax file to cache only (no install)
+      ;;
+    "--release-line")
+      shift
+      releaseLine=$(echo "$1" | awk '{print toupper($0)}')
+      ;;
+    "--yes" | "-y")
+      yesToPrompts=true  # Automatically answer 'yes' to any questions
+      ;;
+    "--download-only")
+      downloadOnly=true  # Download remote pax file to current directory only
+      ;;
+    "--no-set-active")
+      setactive=false  # Install package as normal but keep existing installation as active
+      ;;
+    "--skip-upgrade")
+      skipupgrade=true  # Do not upgrade any packages
+      ;;
+    "--all")
+      all=true  # Install all packages
+      ;;
+    "--select")
+      selectVersion=true  # Display a selction table to allow version picking
+      ;;
+    "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
+      printSyntax "${args}"
+      exit 0
+      ;;
+    "--debug")
+      verbose=true
+      debug=true
+      ;;
+    "-v" | "--v" | "-verbose" | "--verbose")
+      verbose=true
+      ;;
+    "--version")
+      zopen --version $ME
+      exit 0
+      ;;
+    *)
+      chosenRepos="$chosenRepos $1";
+      ;;
   esac
-  shift
+  shift;
 done
 
 if [ -z "${chosenRepos}" ]; then
@@ -574,7 +573,7 @@ if [ -z "${chosenRepos}" ]; then
     killph="kill -HUP $ph"
     addCleanupTrapCmd "$killph"
     chosenRepos="$(${MYDIR}/zopen-query list --installed --no-header --no-versions)"
-    $killph 2>/dev/null # if the timer is not running, the kill will fail
+    $killph 2>/dev/null  # if the timer is not running, the kill will fail
   elif $all; then
     if ! $yesToPrompts; then
       printInfo "Enter 'all' to confirm full installation [takes a long time so be sure!]:"
@@ -622,8 +621,8 @@ printVerbose "Working directory: ${downloadDir}"
 printInfo "- Querying remote repo for latest package information"
 getReposFromGithub
 grfgRc=$?
-$killph 2>/dev/null # if the timer is not running, the kill will fail
-[ 0 -ne $grfgRc ] && exit $grfgRc
+$killph 2>/dev/null  # if the timer is not running, the kill will fail
+[ 0 -ne $grfgRc ] && exit $grfgRc;
 
 foundPort=false
 installArray=""
@@ -639,7 +638,7 @@ else
     printVerbose "Stripping any version (%), tag (#) or port suffixes"
     toolrepo=$(echo "$chosenRepo" | sed -e 's#%.*##' -e 's#=.*##' -e 's#.*port##')
     printVerbose "Adding prefix and 'port' suffix" # quicker than testing for presence!
-    toolfound=$(echo "${repo_results}" | awk -vtoolrepo="$toolrepo" '$0 == toolrepo {print}')
+    toolfound=$(echo "${repo_results}" | awk -vtoolrepo="$toolrepo" '$0 == toolrepo {print}') 
     if [ "$toolfound" = "$toolrepo" ]; then
       printVerbose "Adding '$chosenRepo' to the install queue"
       installArray="$installArray $chosenRepo"
diff --git a/bin/zopen-update-cacert b/bin/zopen-update-cacert
--- a/bin/zopen-update-cacert
+++ b/bin/zopen-update-cacert
@@ -7,36 +7,36 @@
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 checkWritable
 
 # Temporary files
-for tmp in "$TMPDIR" "$TMP" /tmp; do
+for tmp in "$TMPDIR" "$TMP" /tmp
+do
   if [ ! -z "$tmp" ] && [ -d "$tmp" ]; then
     TEMP_CACERT="$tmp/$LOGNAME.$RANDOM.cacert.pem"
     break
   fi
 done
 
-cleanupOnExit()
-{
-  rv=$?
-  [ -f "$TEMP_CACERT" ] && rm -rf "$TEMP_CACERT"
-  exit $rv
+cleanupOnExit() {
+    rv=$?
+    [ -f "$TEMP_CACERT" ] && rm -rf "$TEMP_CACERT"
+    exit $rv
 }
 
 trap "cleanupOnExit" EXIT INT TERM QUIT HUP
 
-printHelp()
+printHelp() 
 {
   args=$*
   echo "zopen-update-cacert:"
@@ -62,7 +62,7 @@ getCACertFromCurl()
   nocertverify=""
   if [ ! -f "$SSL_CERT_FILE" ]; then
     printVerbose "No cacert file present"
-    if $insecureFallback; then
+    if $insecureFallback; then 
       printWarning "Using insecure fallback"
       nocertverify="-k "
     fi
@@ -72,7 +72,7 @@ getCACertFromCurl()
   [ $crc -ne 0 ] && printError "Could not locate curl to download certificate."
 
   printVerbose "Type of curl: $curlver"
-  if ! curlCmd -L $nocertverify -o "$TEMP_CACERT" ${cacert_update_url}; then
+  if ! curlCmd -L $nocertverify -o "$TEMP_CACERT" ${cacert_update_url}  ; then
     printError "curl command could not download from: ${cacert_update_url}"
   fi
 
@@ -89,11 +89,12 @@ updateCACert()
 
 # Main code start here
 verbose=false
-export default_dir="$(cd "${MYDIR}/../" && pwd -P)"
+export default_dir="$( cd "${MYDIR}/../" && pwd -P )"
 export cacert_update_url="https://curl.se/ca/cacert.pem"
 
 # Temporary files
-for tmp in "$TMPDIR" "$TMP" /tmp; do
+for tmp in "$TMPDIR" "$TMP" /tmp
+do
   if [ ! -z "$tmp" ] && [ -d "$tmp" ]; then
     TEMP_CACERT="$tmp/$LOGNAME.$RANDOM.cacert.pem"
     break
@@ -110,40 +111,40 @@ forceUpdate=false
 insecureFallback=false
 while [[ $# -gt 0 ]]; do
   case "$1" in
-  "-f" | "-force" | "--force")
-    forceUpdate=true
-    ;;
-  "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
-    printHelp "${args}"
-    exit 0
-    ;;
-  "--version")
-    zopen --version $ME
-    exit 0
-    ;;
-  "-i" | "--insecure-fallback")
-    insecureFallback=true
-    ;;
-  "-v" | "--v" | "-verbose" | "--verbose")
-    verbose=true
-    ;;
-  *)
-    if [ "${1#-*}" = "$1" ]; then
-      dir="$1"
-    else
-      echo "Unknown option: $1"
+    "-f" | "-force" | "--force")
+      forceUpdate=true;
+      ;;
+    "-h" | "--h" | "-help" | "--help" | "-?" | "-syntax")
       printHelp "${args}"
-      exit 8
-    fi
-    ;;
+      exit 0
+      ;;
+    "--version")
+      zopen --version $ME
+      exit 0
+      ;;
+    "-i" | "--insecure-fallback")
+      insecureFallback=true
+      ;;
+    "-v" | "--v" | "-verbose" | "--verbose")
+      verbose=true
+      ;;
+    *)
+      if [ "${1#-*}" = "$1" ]; then
+        dir="$1"
+      else
+        echo "Unknown option: $1"
+        printHelp "${args}"
+        exit 8
+      fi
+      ;;
   esac
-  shift
+  shift;
 done
 
 ZOPEN_CA="${dir}/cacert.pem"
 
 if ! [ -r "${ZOPEN_CA}" ]; then
-  forceUpdate=true
+  forceUpdate=true 
 fi
 
 printHeader "Getting latest CA Certificate"
@@ -152,6 +153,7 @@ if ! getCACertFromCurl; then
     printError "Curl failed to download CA Certificate"
   fi
 fi
+
 
 if $forceUpdate; then
   updateCACert
diff --git a/bin/zopen-versions b/bin/zopen-versions
--- a/bin/zopen-versions
+++ b/bin/zopen-versions
@@ -4,14 +4,14 @@
 #
 setupMyself()
 {
-  ME=$(basename $0)
-  MYDIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
-  INCDIR="${MYDIR}/../include"
-  if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
-    echo "Internal Error. Unable to find common.sh file to source" >&2
-    exit 8
-  fi
-  . "${INCDIR}/common.sh"
+        ME=$(basename $0)
+        MYDIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 && pwd -P )"
+        INCDIR="${MYDIR}/../include"
+        if ! [ -d "${INCDIR}" ] && ! [ -f "${INCDIR}/common.sh" ]; then
+                echo "Internal Error. Unable to find common.sh file to source" >&2
+                exit 8
+        fi
+        . "${INCDIR}/common.sh"
 }
 setupMyself
 
@@ -48,10 +48,10 @@ fi
 
 if [ -d "${root}" ]; then
   echo "Using ${root} for determining z/OS tarball versions" >&2
-else
+else 
   if [ "x${root}" = "x-?" ] || [ "x${root}" = "x-help" ]; then
     :
-  else
+  else 
     echo "Unable to find ${root} for determining z/OS tarball versions" >&2
   fi
   syntax
@@ -82,9 +82,10 @@ for rawtool in ${tools}; do
     if [ "x${brew_line}" = "x" ]; then
       brew_version="unknown"
     else
-      next_brew_line=$((brew_line + 1))
+      next_brew_line=$((brew_line+1))
       brew_version=$(echo "${brew_version_info}" | sed -n "${next_brew_line}p" | awk -F '<|>' '{print $3}')
     fi
     echo "${tool} zos-version ${version} brew-version ${brew_version}"
   fi
 done
+
