Query JSON cache instead of github api

diff --git a/bin/lib/zopen-download b/bin/lib/zopen-download
--- a/bin/lib/zopen-download
+++ b/bin/lib/zopen-download
@@ -14,7 +14,6 @@ printSyntax()
 {
   args=$*
   echo "zopen download is a utility to download/install a z/OS Open Tools package."
-  echo "If you have a Github OAUTH token, export the environment variable ZOPEN_GIT_OAUTH_TOKEN" >&2
   echo "Syntax: zopen download [<option>]* <package, ...>" >&2
   echo "  where <option> may be one or more of:" >&2
   echo "  -u|--update|--upgrade: updates installed z/OS Open Tools packages."  >&2
@@ -51,19 +50,13 @@ handlePackageInstall(){
   fullname="$1"
   printVerbose "Name to install: $fullname, parsing any version ('=') or tag ('%') has been specified"
   name=$(echo "$fullname" | sed -e 's#[=%].*##')
-  repo="${name}port"
+  repo="${name}"
   versioned=$(echo "$fullname" | cut -s -d '=' -f 2)
   tagged=$(echo "$fullname" | cut -s -d '%' -f 2)
   printVerbose "Name:$name;version:$versioned;tag:$tagged;repo:$repo"
   printHeader "Installing package: $name"
 
   getAllReleasesFromGithub "${repo}"
-  [ 200 -ne "$?" ] && printError "Unable to get list of releases for repo: ${repo}"
-  trimmed=$(echo "$responseBody" | tr -d ' []{}\t\r\n')
-  if [ -z "$trimmed" ]; then
-    printInfo "- No releases published for $name"
-    return
-  fi
 
   originalFileVersion=""
   printVerbose "Checking for meta file at: ${ZOPEN_PKGINSTALL}/${name}/.releaseinfo"
@@ -88,19 +81,16 @@ handlePackageInstall(){
     printVerbose "Finding URL for latest release matching version prefix: requestedVersion:$requestedVersion"
     # list all released filenames, sort them and grab the last (which should be the newest file starting with the
     # specified prefix (fuzzy find rather than exact match)
-    latestfiledetails=$(echo "$contents" | awk -F'/' -v PORT=$name -v REQVER=$versioned '
-      BEGIN{regex = "browser_download_url.*"PORT"-"REQVER".*\.pax\.Z"} {if ( $0 ~ regex ){ print $NF"#@#"$0}}
+    #FIXME: Igor - jq needs oniguruma to support regex
+    latestfiledetails=$(echo "$releases" | awk -F'/' -v PORT=$name -v REQVER=$versioned '
+      BEGIN{regex = ".*"PORT"-"REQVER".*\.pax\.Z"} {if ( $0 ~ regex ){ print $NF"#@#"$0}}
     ' | sort -u | tail -n 1 | tr -d '\"')
-     downloadURL=$(echo "$latestfiledetails" | sed -E 's/.*url: (https.*)/\1/')
+    downloadURL=$(echo "$latestfiledetails" | sed -E 's/.*url: (https.*)/\1/')
   elif [ ! "x" = "x$tagged" ]; then
-    printVerbose "Tagged release $tagged requested - checking existence and URL"
-    taggeddetails=$(echo "$contents" | awk -F'/' -v PORT=$name -v TAG=$tagged '
-      BEGIN{regex = "\"tag_name\": \""PORT"port_"TAG"\""; output=0}
-       { if ( $0 ~ regex ) {output=1;}}
-      /browser_download_url/ {  if (output==1) {print; output=0} }
-      
-    ' | sort -u | tail -n 1 | tr -d '\"')
-    downloadURL="$(echo $taggeddetails | tr -d "\"" | sed -E 's/.*url: (https.*)/\1/')"
+    downloadURL=$(echo "$releases" | jq -e -r '.[] | select(.tag_name == "'$tagged'").assets[0].url')
+    if [ $? -ne 0 ]; then
+      printError "Could not find tag $tagged for repo $repo"
+    fi
   elif $selectVersion; then
     # Explicitly allow the user to select a release to install; useful if there are broken installs
     # as a known good release can be found, selected and pinned!
@@ -111,6 +101,7 @@ handlePackageInstall(){
     [ -p "$TMP_FIFO_PIPE" ] && rm -f "$TMP_FIFO_PIPE"
     mkfifo "$TMP_FIFO_PIPE"
     printVerbose "Getting list of versions"
+    #FIXME: jq needs oniguruma 
     latestfiledetails=$(echo "$contents" | awk -F'/' -v PORT=$name -v REQVER=$versioned '
       BEGIN{regex = "browser_download_url.*"PORT"-"REQVER".*\.pax\.Z"} {if ( $0 ~ regex ){ sub(/\"browser_download_url\":/, ""); print}}
     ' | sort -u | tr -d " ")
@@ -139,21 +130,12 @@ handlePackageInstall(){
     ' | tr -d "\"" )
     printInfo "- Using version: $selection: $downloadURL"
   else
+    downloadURL=$(echo "$releases" | jq -e -r ".[0].assets[0].url")
     printVerbose "No explicit version/tag, using latest"
-    if ! contents="$(getContentsFromGithub "https://api.github.com/repos/ZOSOpenTools/${repo}/releases/latest")"; then
-      exit 4;
-    fi
-    if [ -z "$contents" ]; then
+    
+    if [ -z "$downloadURL" ]; then
       printInfo "- No latest release published for $name"
       exit 4
-    else
-      statusline="$(echo "$contents" | grep "\"body\":.*Test Status:.*(.*)<br />")"
-      downloadURL="$(echo "$contents" | grep "\"browser_download_url\":" | cut -d '"' -f 4)"
-      printVerbose "Check for browser_download_url tag returned: $downloadURL"
-      if [ "" = "${downloadURL}" ]; then
-        printVerbose "Could not locate 'browser_download_url'. Parse 'body'..."
-        downloadURL="$(echo "$statusline" | sed -e "s#.*curl -o - -L ##" -e "s#\.zos\.pax\.Z.*#\.zos\.pax\.Z#")"
-      fi
     fi
   fi
 
@@ -457,13 +439,6 @@ export SSL_CERT_FILE="${ZOPEN_CA}"
 export GIT_SSL_CAINFO="${ZOPEN_CA}"
 export CURL_CA_BUNDLE="${ZOPEN_CA}"
 
-if [ -n "${ZOPEN_GIT_OAUTH_TOKEN}" ]; then
-  OAUTH_TOKEN_OPTION='-H'
-  OAUTH_TOKEN="Authorization: Bearer ${ZOPEN_GIT_OAUTH_TOKEN}" 
-else
-  printWarning "Setting ZOPEN_GIT_OAUTH_TOKEN is recommended to ensure that you do not hit the GitHub API cap. See --help for more details."
-fi
-
 if $downloadOnly | $localInstall; then
   downloadDir=$PWD
 else
@@ -487,11 +462,11 @@ fi
 printVerbose "Working directory: ${downloadDir}"
 # Parse passed in repositories and check if valid zopen framework repos
 printInfo "- Querying remote repo for latest package information"
-progressHandler "network" "- Latest information downloaded" &
-ph=$!
-killph="kill -HUP $ph"
-addCleanupTrapCmd "$killph"
-repo_results="$(getReposFromGithub)"
+#progressHandler "network" "- Latest information downloaded" &
+#ph=$!
+#killph="kill -HUP $ph"
+#addCleanupTrapCmd "$killph"
+getReposFromGithub
 grfgRc=$?
 $killph 2>/dev/null  # if the timer is not running, the kill will fail
 [ 0 -ne $grfgRc ] && exit $grfgRc;
@@ -501,13 +476,6 @@ installArray=""
 
 if $all; then
   for repo in $(echo ${repo_results}); do
-    repo=${repo#"ZOSOpenTools/"}
-    name=${repo%port}
-    # Skip repos that do not end with port
-    if [ "${name}" = "${repo}" ]; then
-      printVerbose "Found non-port repo: ${repo}"
-      continue;
-    fi
     installArray="$installArray $name"
   done
 else
@@ -516,7 +484,6 @@ else
     printVerbose "Stripping any version (%), tag (#) or port suffixes"
     toolrepo=$(echo "$chosenRepo" | sed -e 's#%.*##' -e 's#=.*##' -e 's#.*port##')
     printVerbose "Adding prefix and 'port' suffix" # quicker than testing for presence!
-    toolrepo="ZOSOpenTools/${toolrepo}port"
     toolfound=$(echo "${repo_results}" | awk -vtoolrepo="$toolrepo" '$0 ~ toolrepo {print}') 
     if [ "$toolfound" = "$toolrepo" ]; then
       printVerbose "Adding '$chosenRepo' to the install queue"
